-- Date-effective lineup snapshots.
-- Run after supabase/schema.sql and supabase/admin_auth.sql.

CREATE TABLE IF NOT EXISTS team_daily_lineups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_slug TEXT NOT NULL,
  lineup_date DATE NOT NULL,
  lineup JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_by UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_team_daily_lineups UNIQUE (team_slug, lineup_date)
);

CREATE INDEX IF NOT EXISTS ix_team_daily_lineups_lookup
  ON team_daily_lineups (team_slug, lineup_date DESC);

ALTER TABLE team_daily_lineups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read daily lineups" ON team_daily_lineups;
CREATE POLICY "Public can read daily lineups"
ON team_daily_lineups FOR SELECT TO anon, authenticated
USING (TRUE);

DROP POLICY IF EXISTS "Authenticated users can save daily lineups" ON team_daily_lineups;
CREATE POLICY "Authenticated users can save daily lineups"
ON team_daily_lineups FOR INSERT TO authenticated
WITH CHECK (updated_by = auth.uid());

DROP POLICY IF EXISTS "Lineup creator or admin can update daily lineups" ON team_daily_lineups;
CREATE POLICY "Lineup creator or admin can update daily lineups"
ON team_daily_lineups FOR UPDATE TO authenticated
USING (updated_by = auth.uid() OR public.is_admin_user(auth.uid()))
WITH CHECK (updated_by = auth.uid() OR public.is_admin_user(auth.uid()));

GRANT SELECT ON team_daily_lineups TO anon, authenticated;
GRANT INSERT, UPDATE ON team_daily_lineups TO authenticated;
