-- Date-effective lineup snapshots.
-- Run after supabase/schema.sql, supabase/admin_auth.sql, and supabase/roster_management.sql.

CREATE TABLE IF NOT EXISTS team_daily_lineups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_slug TEXT NOT NULL,
  lineup_date DATE NOT NULL,
  lineup JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_by UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_team_daily_lineups UNIQUE (team_slug, lineup_date)
);

CREATE INDEX IF NOT EXISTS ix_team_daily_lineups_lookup
  ON team_daily_lineups (team_slug, lineup_date DESC);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_publication
    WHERE pubname = 'supabase_realtime'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'team_daily_lineups'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE team_daily_lineups;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.owns_team_slug(target_team_slug TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM teams t
    JOIN team_owner_users tou ON tou.team_id = t.id
    WHERE lower(regexp_replace(t.name, '[^a-zA-Z0-9]+', '-', 'g')) = lower(target_team_slug)
      AND tou.user_id = auth.uid()
      AND tou.active = TRUE
      AND tou.role IN ('owner', 'co_owner')
  );
$$;

GRANT EXECUTE ON FUNCTION public.owns_team_slug(TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.can_view_team_slug_lineup(target_team_slug TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    public.is_admin_user(auth.uid())
    OR EXISTS (
      SELECT 1
      FROM teams t
      JOIN season_team_assignments sta ON sta.team_id = t.id
      WHERE lower(regexp_replace(t.name, '[^a-zA-Z0-9]+', '-', 'g')) = lower(target_team_slug)
        AND public.can_view_league_rosters(sta.season_id, sta.league_code)
    );
$$;

GRANT EXECUTE ON FUNCTION public.can_view_team_slug_lineup(TEXT) TO authenticated;

ALTER TABLE team_daily_lineups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read daily lineups" ON team_daily_lineups;
DROP POLICY IF EXISTS "League owners can read daily lineups" ON team_daily_lineups;
CREATE POLICY "League owners can read daily lineups"
ON team_daily_lineups FOR SELECT TO authenticated
USING (public.can_view_team_slug_lineup(team_slug));

DROP POLICY IF EXISTS "Authenticated users can save daily lineups" ON team_daily_lineups;
DROP POLICY IF EXISTS "Owners can save own daily lineups" ON team_daily_lineups;
CREATE POLICY "Owners can save own daily lineups"
ON team_daily_lineups FOR INSERT TO authenticated
WITH CHECK (
  updated_by = auth.uid()
  AND (
    public.owns_team_slug(team_slug)
    OR public.is_commissioner_user(auth.uid())
  )
);

DROP POLICY IF EXISTS "Lineup creator or admin can update daily lineups" ON team_daily_lineups;
DROP POLICY IF EXISTS "Owners can update own daily lineups" ON team_daily_lineups;
CREATE POLICY "Owners can update own daily lineups"
ON team_daily_lineups FOR UPDATE TO authenticated
USING (
  public.owns_team_slug(team_slug)
  OR public.is_commissioner_user(auth.uid())
)
WITH CHECK (
  updated_by = auth.uid()
  AND (
    public.owns_team_slug(team_slug)
    OR public.is_commissioner_user(auth.uid())
  )
);

REVOKE SELECT ON team_daily_lineups FROM anon;
GRANT SELECT ON team_daily_lineups TO authenticated;
GRANT INSERT, UPDATE ON team_daily_lineups TO authenticated;
