-- Commissioner-managed Event Card deck, hands, and audit history.
-- Run after supabase/schema.sql, supabase/admin_auth.sql, and supabase/league_management.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS public.event_card_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  image_url TEXT NULL,
  total_copies INT NOT NULL DEFAULT 0 CHECK (total_copies >= 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.event_card_holdings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_type_id BIGINT NOT NULL REFERENCES public.event_card_types(id),
  team_id BIGINT NOT NULL REFERENCES public.teams(id),
  status TEXT NOT NULL DEFAULT 'held' CHECK (status IN ('held', 'played', 'returned')),
  assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  assigned_by UUID NULL REFERENCES auth.users(id),
  released_at TIMESTAMP WITH TIME ZONE NULL,
  released_by UUID NULL REFERENCES auth.users(id),
  release_reason TEXT NULL,
  notes TEXT NULL
);

CREATE INDEX IF NOT EXISTS ix_event_card_holdings_active
  ON public.event_card_holdings (card_type_id, team_id)
  WHERE status = 'held';

CREATE TABLE IF NOT EXISTS public.event_card_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holding_id BIGINT NULL REFERENCES public.event_card_holdings(id),
  card_type_id BIGINT NOT NULL REFERENCES public.event_card_types(id),
  team_id BIGINT NOT NULL REFERENCES public.teams(id),
  action TEXT NOT NULL CHECK (action IN ('assigned_random', 'assigned_specific', 'played', 'returned')),
  performed_by UUID NULL REFERENCES auth.users(id),
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  details JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE public.event_card_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_card_holdings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_card_activity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Commissioner manages event card types" ON public.event_card_types;
CREATE POLICY "Commissioner manages event card types" ON public.event_card_types
FOR ALL TO authenticated
USING (public.is_commissioner_user(auth.uid()))
WITH CHECK (public.is_commissioner_user(auth.uid()));

DROP POLICY IF EXISTS "Commissioner reads event card holdings" ON public.event_card_holdings;
CREATE POLICY "Commissioner reads event card holdings" ON public.event_card_holdings
FOR SELECT TO authenticated USING (public.is_commissioner_user(auth.uid()));

DROP POLICY IF EXISTS "Commissioner reads event card activity" ON public.event_card_activity;
CREATE POLICY "Commissioner reads event card activity" ON public.event_card_activity
FOR SELECT TO authenticated USING (public.is_commissioner_user(auth.uid()));

CREATE OR REPLACE VIEW public.event_card_inventory
WITH (security_invoker = true) AS
SELECT
  ect.id AS card_type_id,
  ect.slug,
  ect.name,
  ect.image_url,
  ect.total_copies,
  COUNT(ech.id) FILTER (WHERE ech.status = 'held')::INT AS held_copies,
  GREATEST(0, ect.total_copies - COUNT(ech.id) FILTER (WHERE ech.status = 'held'))::INT AS available_copies,
  ect.active,
  ect.updated_at
FROM public.event_card_types ect
LEFT JOIN public.event_card_holdings ech ON ech.card_type_id = ect.id
GROUP BY ect.id;

CREATE OR REPLACE VIEW public.event_card_hands
WITH (security_invoker = true) AS
SELECT
  ech.id AS holding_id,
  ech.card_type_id,
  ect.name AS card_name,
  ect.image_url,
  ech.team_id,
  t.name AS team_name,
  ech.assigned_at,
  ech.assigned_by,
  ech.notes
FROM public.event_card_holdings ech
JOIN public.event_card_types ect ON ect.id = ech.card_type_id
JOIN public.teams t ON t.id = ech.team_id
WHERE ech.status = 'held';

CREATE OR REPLACE FUNCTION public.commissioner_set_event_card_total(p_card_type_id BIGINT, p_total_copies INT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE held_count INT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF p_total_copies < 0 THEN RAISE EXCEPTION 'Total copies cannot be negative.'; END IF;
  SELECT COUNT(*)::INT INTO held_count FROM public.event_card_holdings
  WHERE card_type_id = p_card_type_id AND status = 'held';
  IF p_total_copies < held_count THEN
    RAISE EXCEPTION 'Total copies cannot be less than the % copies currently held.', held_count;
  END IF;
  UPDATE public.event_card_types SET total_copies = p_total_copies, updated_at = NOW()
  WHERE id = p_card_type_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.commissioner_assign_event_card(p_team_id BIGINT, p_card_type_id BIGINT DEFAULT NULL)
RETURNS TABLE (holding_id BIGINT, card_type_id BIGINT, card_name TEXT, team_id BIGINT, team_name TEXT, remaining_in_deck INT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE selected_type_id BIGINT; new_holding_id BIGINT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.teams WHERE id = p_team_id AND active) THEN RAISE EXCEPTION 'Select an active team.'; END IF;
  IF NOT public.team_event_cards_enabled(p_team_id) THEN RAISE EXCEPTION 'Event Cards are disabled for this team''s league.'; END IF;
  PERFORM pg_advisory_xact_lock(hashtext('owners-club-event-card-deck'));

  IF p_card_type_id IS NULL THEN
    SELECT weighted.card_type_id INTO selected_type_id
    FROM (
      SELECT ect.id AS card_type_id
      FROM public.event_card_types ect
      CROSS JOIN LATERAL generate_series(
        1,
        GREATEST(0, ect.total_copies - (SELECT COUNT(*)::INT FROM public.event_card_holdings h WHERE h.card_type_id = ect.id AND h.status = 'held'))
      ) copies
      WHERE ect.active
    ) weighted
    ORDER BY random() LIMIT 1;
  ELSE
    SELECT ect.id INTO selected_type_id FROM public.event_card_types ect
    WHERE ect.id = p_card_type_id AND ect.active
      AND ect.total_copies > (SELECT COUNT(*) FROM public.event_card_holdings h WHERE h.card_type_id = ect.id AND h.status = 'held');
  END IF;

  IF selected_type_id IS NULL THEN RAISE EXCEPTION 'No copies are available in the deck.'; END IF;
  INSERT INTO public.event_card_holdings (card_type_id, team_id, assigned_by)
  VALUES (selected_type_id, p_team_id, auth.uid()) RETURNING id INTO new_holding_id;
  INSERT INTO public.event_card_activity (holding_id, card_type_id, team_id, action, performed_by)
  VALUES (new_holding_id, selected_type_id, p_team_id, CASE WHEN p_card_type_id IS NULL THEN 'assigned_random' ELSE 'assigned_specific' END, auth.uid());

  RETURN QUERY SELECT h.id, ect.id, ect.name, t.id, t.name,
    GREATEST(0, ect.total_copies - (SELECT COUNT(*)::INT FROM public.event_card_holdings x WHERE x.card_type_id = ect.id AND x.status = 'held'))::INT
  FROM public.event_card_holdings h JOIN public.event_card_types ect ON ect.id = h.card_type_id
  JOIN public.teams t ON t.id = h.team_id WHERE h.id = new_holding_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.commissioner_release_event_card(p_holding_id BIGINT, p_action TEXT DEFAULT 'played')
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE current_holding public.event_card_holdings%ROWTYPE;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF p_action NOT IN ('played', 'returned') THEN RAISE EXCEPTION 'Action must be played or returned.'; END IF;
  SELECT * INTO current_holding FROM public.event_card_holdings WHERE id = p_holding_id AND status = 'held' FOR UPDATE;
  IF current_holding.id IS NULL THEN RAISE EXCEPTION 'That card is no longer in a team hand.'; END IF;
  UPDATE public.event_card_holdings SET status = p_action, released_at = NOW(), released_by = auth.uid(), release_reason = p_action
  WHERE id = p_holding_id;
  INSERT INTO public.event_card_activity (holding_id, card_type_id, team_id, action, performed_by)
  VALUES (current_holding.id, current_holding.card_type_id, current_holding.team_id, p_action, auth.uid());
END;
$$;

GRANT SELECT, INSERT, UPDATE ON public.event_card_types TO authenticated;
GRANT SELECT ON public.event_card_holdings, public.event_card_activity, public.event_card_inventory, public.event_card_hands TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.event_card_types_id_seq, public.event_card_holdings_id_seq, public.event_card_activity_id_seq TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_set_event_card_total(BIGINT, INT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_assign_event_card(BIGINT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_release_event_card(BIGINT, TEXT) TO authenticated;

COMMIT;
