-- Stored calculated fantasy scores.
-- Run after supabase/schema.sql and supabase/roster_management.sql.

CREATE TABLE IF NOT EXISTS game_score_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_number INT NOT NULL,
  game_number INT NOT NULL,
  week_number INT NOT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'mlb_stats_api',
  status VARCHAR(20) NOT NULL DEFAULT 'complete'
    CHECK (status IN ('pending', 'complete', 'failed')),
  started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE NULL,
  error_message TEXT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_game_score_runs_lookup
  ON game_score_runs (season_number, game_number, week_number, started_at DESC);

CREATE TABLE IF NOT EXISTS game_matchup_score_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NULL REFERENCES game_score_runs(id) ON DELETE SET NULL,
  season_number INT NOT NULL,
  game_number INT NOT NULL,
  week_number INT NOT NULL,
  matchup_key VARCHAR(80) NOT NULL,
  league_code VARCHAR(20) NULL,
  away_team_name VARCHAR(160) NOT NULL,
  home_team_name VARCHAR(160) NOT NULL,
  away_score NUMERIC(10,2) NOT NULL DEFAULT 0,
  home_score NUMERIC(10,2) NOT NULL DEFAULT 0,
  away_psr NUMERIC(10,2) NULL,
  home_psr NUMERIC(10,2) NULL,
  away_lead NUMERIC(10,2) NULL,
  home_lead NUMERIC(10,2) NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  calculated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_game_matchup_score_results UNIQUE (season_number, game_number, matchup_key)
);

CREATE TABLE IF NOT EXISTS game_team_daily_score_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NULL REFERENCES game_score_runs(id) ON DELETE SET NULL,
  season_number INT NOT NULL,
  game_number INT NOT NULL,
  week_number INT NOT NULL,
  matchup_key VARCHAR(80) NOT NULL,
  team_name VARCHAR(160) NOT NULL,
  home_away CHAR(1) NOT NULL CHECK (home_away IN ('H', 'A')),
  stat_date DATE NOT NULL,
  sheet_points NUMERIC(10,2) NULL,
  calculated_points NUMERIC(10,2) NOT NULL DEFAULT 0,
  offense_points NUMERIC(10,2) NOT NULL DEFAULT 0,
  pitching_points NUMERIC(10,2) NOT NULL DEFAULT 0,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  calculated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_game_team_daily_score_results UNIQUE (season_number, game_number, matchup_key, team_name, stat_date)
);

CREATE TABLE IF NOT EXISTS game_player_daily_score_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NULL REFERENCES game_score_runs(id) ON DELETE SET NULL,
  season_number INT NOT NULL,
  game_number INT NOT NULL,
  week_number INT NOT NULL,
  matchup_key VARCHAR(80) NOT NULL,
  team_name VARCHAR(160) NOT NULL,
  player_name VARCHAR(160) NOT NULL,
  roster_slot VARCHAR(20) NULL,
  stat_date DATE NOT NULL,
  sheet_points NUMERIC(10,2) NULL,
  calculated_points NUMERIC(10,2) NOT NULL DEFAULT 0,
  scoring_breakdown JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_stats JSONB NOT NULL DEFAULT '{}'::jsonb,
  calculated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_game_player_daily_score_results UNIQUE (
    season_number,
    game_number,
    matchup_key,
    team_name,
    player_name,
    roster_slot,
    stat_date
  )
);

ALTER TABLE game_player_daily_score_results
  DROP CONSTRAINT IF EXISTS uq_game_player_daily_score_results;

ALTER TABLE game_player_daily_score_results
  ADD CONSTRAINT uq_game_player_daily_score_results UNIQUE (
    season_number,
    game_number,
    matchup_key,
    team_name,
    player_name,
    roster_slot,
    stat_date
  );

ALTER TABLE game_score_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_matchup_score_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_team_daily_score_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_player_daily_score_results ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read game score runs" ON game_score_runs;
CREATE POLICY "Public can read game score runs"
ON game_score_runs FOR SELECT TO anon, authenticated
USING (TRUE);

DROP POLICY IF EXISTS "Public can read matchup scores" ON game_matchup_score_results;
CREATE POLICY "Public can read matchup scores"
ON game_matchup_score_results FOR SELECT TO anon, authenticated
USING (TRUE);

DROP POLICY IF EXISTS "Public can read team daily scores" ON game_team_daily_score_results;
CREATE POLICY "Public can read team daily scores"
ON game_team_daily_score_results FOR SELECT TO anon, authenticated
USING (TRUE);

DROP POLICY IF EXISTS "Public can read player daily scores" ON game_player_daily_score_results;
CREATE POLICY "Public can read player daily scores"
ON game_player_daily_score_results FOR SELECT TO anon, authenticated
USING (TRUE);
