-- Editable season league, conference, division, and team placement structure.
-- Run after supabase/schema.sql, supabase/admin_auth.sql, and supabase/roster_management.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS public.season_leagues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NOT NULL REFERENCES public.seasons(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  flag_image_url TEXT NULL,
  event_cards_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  keeper_contracts_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE (season_id, code),
  UNIQUE (season_id, name)
);

CREATE TABLE IF NOT EXISTS public.season_conferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id BIGINT NOT NULL REFERENCES public.season_leagues(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE (league_id, code),
  UNIQUE (league_id, name)
);

CREATE TABLE IF NOT EXISTS public.season_divisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conference_id BIGINT NOT NULL REFERENCES public.season_conferences(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE (conference_id, code),
  UNIQUE (conference_id, name)
);

ALTER TABLE public.season_team_assignments ADD COLUMN IF NOT EXISTS league_id BIGINT NULL REFERENCES public.season_leagues(id);
ALTER TABLE public.season_team_assignments ADD COLUMN IF NOT EXISTS conference_id BIGINT NULL REFERENCES public.season_conferences(id);
ALTER TABLE public.season_team_assignments ADD COLUMN IF NOT EXISTS division_id BIGINT NULL REFERENCES public.season_divisions(id);

INSERT INTO public.season_leagues (season_id, code, name, sort_order)
SELECT DISTINCT sta.season_id, lower(regexp_replace(sta.league_code, '[^a-zA-Z0-9]+', '-', 'g')), sta.league_code,
  dense_rank() OVER (PARTITION BY sta.season_id ORDER BY sta.league_code)
FROM public.season_team_assignments sta
ON CONFLICT (season_id, code) DO NOTHING;

UPDATE public.season_leagues SET flag_image_url = CASE
  WHEN lower(name) = 'keystone' THEN '/assets/Keystone.png'
  WHEN lower(name) = 'diamond' THEN '/assets/Diamond.png'
  ELSE flag_image_url END
WHERE flag_image_url IS NULL;

INSERT INTO public.season_conferences (league_id, code, name, sort_order)
SELECT DISTINCT sl.id, lower(regexp_replace(sta.conference_code, '[^a-zA-Z0-9]+', '-', 'g')), sta.conference_code,
  dense_rank() OVER (PARTITION BY sl.id ORDER BY sta.conference_code)
FROM public.season_team_assignments sta
JOIN public.season_leagues sl ON sl.season_id = sta.season_id AND lower(sl.name) = lower(sta.league_code)
ON CONFLICT (league_id, code) DO NOTHING;

INSERT INTO public.season_divisions (conference_id, code, name, sort_order)
SELECT DISTINCT sc.id, lower(regexp_replace(sta.division_code, '[^a-zA-Z0-9]+', '-', 'g')), sta.division_code,
  dense_rank() OVER (PARTITION BY sc.id ORDER BY sta.division_code)
FROM public.season_team_assignments sta
JOIN public.season_leagues sl ON sl.season_id = sta.season_id AND lower(sl.name) = lower(sta.league_code)
JOIN public.season_conferences sc ON sc.league_id = sl.id AND lower(sc.name) = lower(sta.conference_code)
ON CONFLICT (conference_id, code) DO NOTHING;

UPDATE public.season_team_assignments sta SET
  league_id = sl.id, conference_id = sc.id, division_id = sd.id
FROM public.season_leagues sl
JOIN public.season_conferences sc ON sc.league_id = sl.id
JOIN public.season_divisions sd ON sd.conference_id = sc.id
WHERE sl.season_id = sta.season_id
  AND lower(sl.name) = lower(sta.league_code)
  AND lower(sc.name) = lower(sta.conference_code)
  AND lower(sd.name) = lower(sta.division_code);

ALTER TABLE public.season_leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.season_conferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.season_divisions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public reads season leagues" ON public.season_leagues;
DROP POLICY IF EXISTS "Public reads season conferences" ON public.season_conferences;
DROP POLICY IF EXISTS "Public reads season divisions" ON public.season_divisions;
DROP POLICY IF EXISTS "Commissioner manages season leagues" ON public.season_leagues;
DROP POLICY IF EXISTS "Commissioner manages season conferences" ON public.season_conferences;
DROP POLICY IF EXISTS "Commissioner manages season divisions" ON public.season_divisions;
CREATE POLICY "Public reads season leagues" ON public.season_leagues FOR SELECT TO anon, authenticated USING (TRUE);
CREATE POLICY "Public reads season conferences" ON public.season_conferences FOR SELECT TO anon, authenticated USING (TRUE);
CREATE POLICY "Public reads season divisions" ON public.season_divisions FOR SELECT TO anon, authenticated USING (TRUE);
CREATE POLICY "Commissioner manages season leagues" ON public.season_leagues FOR ALL TO authenticated USING (public.is_commissioner_user(auth.uid())) WITH CHECK (public.is_commissioner_user(auth.uid()));
CREATE POLICY "Commissioner manages season conferences" ON public.season_conferences FOR ALL TO authenticated USING (public.is_commissioner_user(auth.uid())) WITH CHECK (public.is_commissioner_user(auth.uid()));
CREATE POLICY "Commissioner manages season divisions" ON public.season_divisions FOR ALL TO authenticated USING (public.is_commissioner_user(auth.uid())) WITH CHECK (public.is_commissioner_user(auth.uid()));

CREATE OR REPLACE VIEW public.public_season_league_structure AS
SELECT sl.season_id, s.season_number, sl.id AS league_id, sl.code AS league_code, sl.name AS league_name,
  sl.flag_image_url, sl.event_cards_enabled, sl.keeper_contracts_enabled, sl.sort_order AS league_sort,
  sc.id AS conference_id, sc.code AS conference_code, sc.name AS conference_name, sc.sort_order AS conference_sort,
  sd.id AS division_id, sd.code AS division_code, sd.name AS division_name, sd.sort_order AS division_sort
FROM public.season_leagues sl JOIN public.seasons s ON s.id = sl.season_id
LEFT JOIN public.season_conferences sc ON sc.league_id = sl.id
LEFT JOIN public.season_divisions sd ON sd.conference_id = sc.id;

CREATE OR REPLACE FUNCTION public.commissioner_update_league(p_league_id BIGINT, p_name TEXT, p_flag_image_url TEXT, p_event_cards_enabled BOOLEAN, p_keeper_contracts_enabled BOOLEAN)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF nullif(trim(p_name), '') IS NULL THEN RAISE EXCEPTION 'League name is required.'; END IF;
  UPDATE public.season_leagues SET name = trim(p_name), flag_image_url = nullif(trim(p_flag_image_url), ''),
    event_cards_enabled = p_event_cards_enabled, keeper_contracts_enabled = p_keeper_contracts_enabled, updated_at = NOW()
  WHERE id = p_league_id;
  UPDATE public.season_team_assignments SET league_code = trim(p_name) WHERE league_id = p_league_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_update_conference(p_conference_id BIGINT, p_name TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF nullif(trim(p_name), '') IS NULL THEN RAISE EXCEPTION 'Conference name is required.'; END IF;
  UPDATE public.season_conferences SET name = trim(p_name), updated_at = NOW() WHERE id = p_conference_id;
  UPDATE public.season_team_assignments SET conference_code = trim(p_name) WHERE conference_id = p_conference_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_update_division(p_division_id BIGINT, p_name TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF nullif(trim(p_name), '') IS NULL THEN RAISE EXCEPTION 'Division name is required.'; END IF;
  UPDATE public.season_divisions SET name = trim(p_name), updated_at = NOW() WHERE id = p_division_id;
  UPDATE public.season_team_assignments SET division_code = trim(p_name) WHERE division_id = p_division_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_assign_team_division(p_assignment_id BIGINT, p_division_id BIGINT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE target_division public.season_divisions%ROWTYPE; target_conference public.season_conferences%ROWTYPE; target_league public.season_leagues%ROWTYPE; assignment_season BIGINT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  SELECT season_id INTO assignment_season FROM public.season_team_assignments WHERE id = p_assignment_id;
  SELECT * INTO target_division FROM public.season_divisions WHERE id = p_division_id;
  SELECT * INTO target_conference FROM public.season_conferences WHERE id = target_division.conference_id;
  SELECT * INTO target_league FROM public.season_leagues WHERE id = target_conference.league_id;
  IF assignment_season IS NULL OR target_league.season_id <> assignment_season THEN RAISE EXCEPTION 'Division and team must belong to the same season.'; END IF;
  UPDATE public.season_team_assignments SET division_id = target_division.id, conference_id = target_conference.id, league_id = target_league.id,
    division_code = target_division.name, conference_code = target_conference.name, league_code = target_league.name
  WHERE id = p_assignment_id;
END; $$;

CREATE OR REPLACE FUNCTION public.team_event_cards_enabled(p_team_id BIGINT)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE((SELECT sl.event_cards_enabled FROM public.season_team_assignments sta
    JOIN public.seasons s ON s.id = sta.season_id JOIN public.season_leagues sl ON sl.id = sta.league_id
    WHERE sta.team_id = p_team_id AND s.status = 'active' LIMIT 1), FALSE);
$$;

CREATE OR REPLACE FUNCTION public.enforce_keeper_contract_setting()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
DECLARE keeper_allowed BOOLEAN;
BEGIN
  IF NEW.contract_years IS NULL OR upper(trim(NEW.contract_years)) = 'X' THEN RETURN NEW; END IF;
  SELECT COALESCE(sl.keeper_contracts_enabled, FALSE) INTO keeper_allowed
  FROM public.season_team_assignments sta LEFT JOIN public.season_leagues sl ON sl.id = sta.league_id
  WHERE sta.season_id = NEW.season_id AND sta.team_id = NEW.team_id;
  IF NOT keeper_allowed THEN RAISE EXCEPTION 'Contract years are disabled for this league.'; END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_enforce_keeper_contract_setting ON public.roster_memberships;
CREATE TRIGGER trg_enforce_keeper_contract_setting BEFORE INSERT OR UPDATE OF contract_years, team_id, league_code
ON public.roster_memberships FOR EACH ROW EXECUTE FUNCTION public.enforce_keeper_contract_setting();

GRANT SELECT ON public.season_leagues, public.season_conferences, public.season_divisions, public.public_season_league_structure TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_update_league(BIGINT, TEXT, TEXT, BOOLEAN, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_update_conference(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_update_division(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_assign_team_division(BIGINT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.team_event_cards_enabled(BIGINT) TO authenticated;

COMMIT;
