-- Major League -> Season -> League -> Conference -> Division management,
-- effective-dated scoring sources, and commissioner roster transactions.
-- Run after schema.sql, admin_auth.sql, roster_management.sql, and league_management.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS public.major_leagues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

INSERT INTO public.major_leagues (code, name, sort_order)
VALUES ('owners-club', 'Owner''s Club', 1)
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.seasons ADD COLUMN IF NOT EXISTS major_league_id BIGINT NULL REFERENCES public.major_leagues(id);
UPDATE public.seasons
SET major_league_id = (SELECT id FROM public.major_leagues WHERE code = 'owners-club')
WHERE major_league_id IS NULL;

ALTER TABLE public.seasons ALTER COLUMN major_league_id SET NOT NULL;
ALTER TABLE public.seasons DROP CONSTRAINT IF EXISTS uq_seasons_number;
CREATE UNIQUE INDEX IF NOT EXISTS uq_seasons_major_league_number
  ON public.seasons (major_league_id, season_number);

ALTER TABLE public.season_leagues ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.season_conferences ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.season_divisions ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS public.league_data_source_periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id BIGINT NOT NULL REFERENCES public.season_leagues(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL CHECK (source_type IN ('mlb_stats_api', 'simulation', 'spreadsheet', 'manual', 'other_api')),
  source_name TEXT NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NULL,
  priority INT NOT NULL DEFAULT 100,
  configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by UUID NULL REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CHECK (ends_on IS NULL OR ends_on >= starts_on)
);

CREATE INDEX IF NOT EXISTS ix_league_data_source_periods_lookup
  ON public.league_data_source_periods (league_id, starts_on, ends_on, priority);

INSERT INTO public.league_data_source_periods (league_id, source_type, source_name, starts_on, ends_on, priority)
SELECT sl.id, 'mlb_stats_api', 'MLB Stats API', COALESCE(s.starts_on, make_date(s.season_number + 1994, 3, 1)), s.ends_on, 100
FROM public.season_leagues sl
JOIN public.seasons s ON s.id = sl.season_id
WHERE NOT EXISTS (SELECT 1 FROM public.league_data_source_periods p WHERE p.league_id = sl.id);

ALTER TABLE public.major_leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.league_data_source_periods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public reads major leagues" ON public.major_leagues;
CREATE POLICY "Public reads major leagues" ON public.major_leagues FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "Commissioner manages major leagues" ON public.major_leagues;
CREATE POLICY "Commissioner manages major leagues" ON public.major_leagues FOR ALL TO authenticated
USING (public.is_commissioner_user(auth.uid())) WITH CHECK (public.is_commissioner_user(auth.uid()));
DROP POLICY IF EXISTS "Public reads league data sources" ON public.league_data_source_periods;
CREATE POLICY "Public reads league data sources" ON public.league_data_source_periods FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "Commissioner manages league data sources" ON public.league_data_source_periods;
CREATE POLICY "Commissioner manages league data sources" ON public.league_data_source_periods FOR ALL TO authenticated
USING (public.is_commissioner_user(auth.uid())) WITH CHECK (public.is_commissioner_user(auth.uid()));

DROP VIEW IF EXISTS public.public_season_league_structure;
CREATE VIEW public.public_season_league_structure WITH (security_invoker = true) AS
SELECT ml.id AS major_league_id, ml.code AS major_league_code, ml.name AS major_league_name, ml.active AS major_league_active,
  sl.season_id, s.season_number, s.name AS season_name, s.status AS season_status,
  sl.id AS league_id, sl.code AS league_code, sl.name AS league_name, sl.flag_image_url,
  sl.event_cards_enabled, sl.keeper_contracts_enabled, sl.active AS league_active, sl.sort_order AS league_sort,
  sc.id AS conference_id, sc.code AS conference_code, sc.name AS conference_name, sc.active AS conference_active, sc.sort_order AS conference_sort,
  sd.id AS division_id, sd.code AS division_code, sd.name AS division_name, sd.active AS division_active, sd.sort_order AS division_sort
FROM public.seasons s
JOIN public.major_leagues ml ON ml.id = s.major_league_id
JOIN public.season_leagues sl ON sl.season_id = s.id
LEFT JOIN public.season_conferences sc ON sc.league_id = sl.id
LEFT JOIN public.season_divisions sd ON sd.conference_id = sc.id;

CREATE OR REPLACE VIEW public.public_league_data_sources WITH (security_invoker = true) AS
SELECT p.id, p.league_id, sl.name AS league_name, sl.season_id, s.season_number,
  s.major_league_id, ml.name AS major_league_name, p.source_type, p.source_name,
  p.starts_on, p.ends_on, p.priority, p.configuration, p.active, p.created_at, p.updated_at
FROM public.league_data_source_periods p
JOIN public.season_leagues sl ON sl.id = p.league_id
JOIN public.seasons s ON s.id = sl.season_id
JOIN public.major_leagues ml ON ml.id = s.major_league_id;

CREATE OR REPLACE FUNCTION public.commissioner_update_major_league(p_major_league_id BIGINT, p_name TEXT, p_active BOOLEAN DEFAULT TRUE)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF nullif(trim(p_name), '') IS NULL THEN RAISE EXCEPTION 'Major League name is required.'; END IF;
  UPDATE public.major_leagues SET name = trim(p_name), active = p_active, updated_at = NOW() WHERE id = p_major_league_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_create_major_league(p_name TEXT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE new_id BIGINT; base_code TEXT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF nullif(trim(p_name), '') IS NULL THEN RAISE EXCEPTION 'Major League name is required.'; END IF;
  base_code := trim(both '-' from lower(regexp_replace(trim(p_name), '[^a-zA-Z0-9]+', '-', 'g')));
  INSERT INTO public.major_leagues(code,name,sort_order) VALUES(base_code,trim(p_name),(SELECT COALESCE(MAX(sort_order),0)+1 FROM public.major_leagues)) RETURNING id INTO new_id;
  RETURN new_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_create_season(p_major_league_id BIGINT, p_season_number INT, p_name TEXT, p_starts_on DATE, p_ends_on DATE)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE new_id BIGINT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  INSERT INTO public.seasons(major_league_id,season_number,name,status,starts_on,ends_on)
  VALUES(p_major_league_id,p_season_number,COALESCE(nullif(trim(p_name),''),'Season '||p_season_number),'planned',p_starts_on,p_ends_on)
  RETURNING id INTO new_id; RETURN new_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_update_season(p_season_id BIGINT, p_season_number INT, p_name TEXT, p_status TEXT, p_starts_on DATE, p_ends_on DATE)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF p_status NOT IN ('planned','active','complete','archived') THEN RAISE EXCEPTION 'Unknown season status.'; END IF;
  IF p_ends_on IS NOT NULL AND p_starts_on IS NOT NULL AND p_ends_on < p_starts_on THEN RAISE EXCEPTION 'End date cannot precede start date.'; END IF;
  UPDATE public.seasons SET season_number=p_season_number,name=COALESCE(nullif(trim(p_name),''),'Season '||p_season_number),
    status=p_status,starts_on=p_starts_on,ends_on=p_ends_on,updated_at=NOW() WHERE id=p_season_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_clone_season_structure(p_source_season_id BIGINT, p_new_season_id BIGINT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF EXISTS (SELECT 1 FROM public.season_leagues WHERE season_id=p_new_season_id) THEN RAISE EXCEPTION 'Target Season already has a League structure.'; END IF;
  INSERT INTO public.season_leagues(season_id,code,name,flag_image_url,event_cards_enabled,keeper_contracts_enabled,sort_order,active)
  SELECT p_new_season_id,code,name,flag_image_url,event_cards_enabled,keeper_contracts_enabled,sort_order,active FROM public.season_leagues WHERE season_id=p_source_season_id;
  INSERT INTO public.season_conferences(league_id,code,name,sort_order,active)
  SELECT nl.id,oc.code,oc.name,oc.sort_order,oc.active FROM public.season_conferences oc
  JOIN public.season_leagues ol ON ol.id=oc.league_id JOIN public.season_leagues nl ON nl.season_id=p_new_season_id AND nl.code=ol.code WHERE ol.season_id=p_source_season_id;
  INSERT INTO public.season_divisions(conference_id,code,name,sort_order,active)
  SELECT nc.id,od.code,od.name,od.sort_order,od.active FROM public.season_divisions od
  JOIN public.season_conferences oc ON oc.id=od.conference_id JOIN public.season_leagues ol ON ol.id=oc.league_id
  JOIN public.season_leagues nl ON nl.season_id=p_new_season_id AND nl.code=ol.code
  JOIN public.season_conferences nc ON nc.league_id=nl.id AND nc.code=oc.code WHERE ol.season_id=p_source_season_id;
  INSERT INTO public.season_team_assignments(season_id,team_id,league_code,conference_code,division_code,league_id,conference_id,division_id,sort_order)
  SELECT p_new_season_id,sta.team_id,nl.name,nc.name,nd.name,nl.id,nc.id,nd.id,sta.sort_order
  FROM public.season_team_assignments sta
  JOIN public.season_leagues ol ON ol.id=sta.league_id JOIN public.season_conferences oc ON oc.id=sta.conference_id JOIN public.season_divisions od ON od.id=sta.division_id
  JOIN public.season_leagues nl ON nl.season_id=p_new_season_id AND nl.code=ol.code
  JOIN public.season_conferences nc ON nc.league_id=nl.id AND nc.code=oc.code JOIN public.season_divisions nd ON nd.conference_id=nc.id AND nd.code=od.code
  WHERE sta.season_id=p_source_season_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_create_league(p_season_id BIGINT, p_name TEXT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE new_id BIGINT; base_code TEXT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  base_code := trim(both '-' from lower(regexp_replace(trim(p_name), '[^a-zA-Z0-9]+', '-', 'g')));
  INSERT INTO public.season_leagues(season_id,code,name,sort_order) VALUES(p_season_id,base_code,trim(p_name),(SELECT COALESCE(MAX(sort_order),0)+1 FROM public.season_leagues WHERE season_id=p_season_id)) RETURNING id INTO new_id;
  RETURN new_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_create_conference(p_league_id BIGINT, p_name TEXT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE new_id BIGINT; base_code TEXT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  base_code := trim(both '-' from lower(regexp_replace(trim(p_name), '[^a-zA-Z0-9]+', '-', 'g')));
  INSERT INTO public.season_conferences(league_id,code,name,sort_order) VALUES(p_league_id,base_code,trim(p_name),(SELECT COALESCE(MAX(sort_order),0)+1 FROM public.season_conferences WHERE league_id=p_league_id)) RETURNING id INTO new_id;
  RETURN new_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_create_division(p_conference_id BIGINT, p_name TEXT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE new_id BIGINT; base_code TEXT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  base_code := trim(both '-' from lower(regexp_replace(trim(p_name), '[^a-zA-Z0-9]+', '-', 'g')));
  INSERT INTO public.season_divisions(conference_id,code,name,sort_order) VALUES(p_conference_id,base_code,trim(p_name),(SELECT COALESCE(MAX(sort_order),0)+1 FROM public.season_divisions WHERE conference_id=p_conference_id)) RETURNING id INTO new_id;
  RETURN new_id;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_set_structure_active(p_entity_type TEXT, p_entity_id BIGINT, p_active BOOLEAN)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  CASE p_entity_type
    WHEN 'league' THEN UPDATE public.season_leagues SET active=p_active,updated_at=NOW() WHERE id=p_entity_id;
    WHEN 'conference' THEN UPDATE public.season_conferences SET active=p_active,updated_at=NOW() WHERE id=p_entity_id;
    WHEN 'division' THEN UPDATE public.season_divisions SET active=p_active,updated_at=NOW() WHERE id=p_entity_id;
    ELSE RAISE EXCEPTION 'Unknown structure type.';
  END CASE;
END; $$;

CREATE OR REPLACE FUNCTION public.commissioner_save_data_source(p_id BIGINT, p_league_id BIGINT, p_source_type TEXT, p_source_name TEXT, p_starts_on DATE, p_ends_on DATE, p_priority INT, p_configuration JSONB DEFAULT '{}'::jsonb, p_active BOOLEAN DEFAULT TRUE)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE saved_id BIGINT;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF p_source_type NOT IN ('mlb_stats_api','simulation','spreadsheet','manual','other_api') THEN RAISE EXCEPTION 'Unknown data source type.'; END IF;
  IF p_ends_on IS NOT NULL AND p_ends_on < p_starts_on THEN RAISE EXCEPTION 'End date cannot precede start date.'; END IF;
  IF p_id IS NULL THEN
    INSERT INTO public.league_data_source_periods(league_id,source_type,source_name,starts_on,ends_on,priority,configuration,active,created_by)
    VALUES(p_league_id,p_source_type,trim(p_source_name),p_starts_on,p_ends_on,p_priority,COALESCE(p_configuration,'{}'::jsonb),p_active,auth.uid()) RETURNING id INTO saved_id;
  ELSE
    UPDATE public.league_data_source_periods SET league_id=p_league_id,source_type=p_source_type,source_name=trim(p_source_name),starts_on=p_starts_on,ends_on=p_ends_on,priority=p_priority,configuration=COALESCE(p_configuration,'{}'::jsonb),active=p_active,updated_at=NOW() WHERE id=p_id RETURNING id INTO saved_id;
  END IF;
  RETURN saved_id;
END; $$;

CREATE OR REPLACE FUNCTION public.league_data_source_for_date(p_league_id BIGINT, p_stat_date DATE)
RETURNS TABLE(source_type TEXT, source_name TEXT, configuration JSONB) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT p.source_type,p.source_name,p.configuration FROM public.league_data_source_periods p
  WHERE p.league_id=p_league_id AND p.active AND p.starts_on<=p_stat_date AND (p.ends_on IS NULL OR p.ends_on>=p_stat_date)
  ORDER BY p.priority DESC,p.starts_on DESC,p.id DESC LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.commissioner_upsert_team_structure(p_team_name TEXT, p_city TEXT, p_nickname TEXT, p_active BOOLEAN, p_season_id BIGINT, p_division_id BIGINT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE saved_team_id BIGINT; saved_assignment_id BIGINT; target_division public.season_divisions%ROWTYPE; target_conference public.season_conferences%ROWTYPE; target_league public.season_leagues%ROWTYPE;
BEGIN
  IF NOT public.is_commissioner_user(auth.uid()) THEN RAISE EXCEPTION 'Commissioner access required.'; END IF;
  IF nullif(trim(p_team_name),'') IS NULL THEN RAISE EXCEPTION 'Team name is required.'; END IF;
  SELECT * INTO target_division FROM public.season_divisions WHERE id=p_division_id AND active;
  SELECT * INTO target_conference FROM public.season_conferences WHERE id=target_division.conference_id AND active;
  SELECT * INTO target_league FROM public.season_leagues WHERE id=target_conference.league_id AND season_id=p_season_id AND active;
  IF target_league.id IS NULL THEN RAISE EXCEPTION 'Choose an active Division in this Season.'; END IF;
  SELECT id INTO saved_team_id FROM public.teams WHERE lower(name)=lower(trim(p_team_name)) LIMIT 1;
  IF saved_team_id IS NULL THEN
    INSERT INTO public.teams(name,city,nickname,active) VALUES(trim(p_team_name),nullif(trim(p_city),''),nullif(trim(p_nickname),''),p_active) RETURNING id INTO saved_team_id;
  ELSE
    UPDATE public.teams SET name=trim(p_team_name),city=nullif(trim(p_city),''),nickname=nullif(trim(p_nickname),''),active=p_active,updated_at=NOW() WHERE id=saved_team_id;
  END IF;
  INSERT INTO public.season_team_assignments(season_id,team_id,league_code,conference_code,division_code,league_id,conference_id,division_id,sort_order)
  VALUES(p_season_id,saved_team_id,target_league.name,target_conference.name,target_division.name,target_league.id,target_conference.id,target_division.id,(SELECT COALESCE(MAX(sort_order),0)+1 FROM public.season_team_assignments WHERE season_id=p_season_id))
  ON CONFLICT(season_id,team_id) DO UPDATE SET league_code=EXCLUDED.league_code,conference_code=EXCLUDED.conference_code,division_code=EXCLUDED.division_code,league_id=EXCLUDED.league_id,conference_id=EXCLUDED.conference_id,division_id=EXCLUDED.division_id
  RETURNING id INTO saved_assignment_id;
  RETURN saved_team_id;
END; $$;

GRANT SELECT ON public.major_leagues, public.league_data_source_periods, public.public_season_league_structure, public.public_league_data_sources TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.major_leagues_id_seq, public.league_data_source_periods_id_seq TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_update_major_league(BIGINT,TEXT,BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_create_major_league(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_create_season(BIGINT,INT,TEXT,DATE,DATE) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_update_season(BIGINT,INT,TEXT,TEXT,DATE,DATE) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_clone_season_structure(BIGINT,BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_create_league(BIGINT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_create_conference(BIGINT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_create_division(BIGINT,TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_set_structure_active(TEXT,BIGINT,BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_save_data_source(BIGINT,BIGINT,TEXT,TEXT,DATE,DATE,INT,JSONB,BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.league_data_source_for_date(BIGINT,DATE) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_upsert_team_structure(TEXT,TEXT,TEXT,BOOLEAN,BIGINT,BIGINT) TO authenticated;

COMMIT;
