-- Roster, lineup, player pool, transactions, and scoring rules.
-- Run after supabase/schema.sql and supabase/admin_auth.sql.

CREATE TABLE IF NOT EXISTS mlb_teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mlb_team_id INT NULL,
  abbreviation VARCHAR(10) NOT NULL,
  name VARCHAR(120) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_mlb_teams_abbreviation UNIQUE (abbreviation)
);

CREATE TABLE IF NOT EXISTS mlb_players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mlb_player_id BIGINT NULL,
  display_name VARCHAR(160) NOT NULL,
  normalized_name VARCHAR(160) NOT NULL,
  bats CHAR(1) NULL CHECK (bats IN ('L', 'R', 'S')),
  throws CHAR(1) NULL CHECK (throws IN ('L', 'R')),
  primary_position VARCHAR(10) NULL,
  eligible_positions TEXT[] NOT NULL DEFAULT '{}',
  mlb_team_id BIGINT NULL REFERENCES mlb_teams(id),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_mlb_players_provider UNIQUE (mlb_player_id),
  CONSTRAINT uq_mlb_players_normalized UNIQUE (normalized_name)
);

CREATE INDEX IF NOT EXISTS ix_mlb_players_active
  ON mlb_players (active, normalized_name);

CREATE TABLE IF NOT EXISTS team_owner_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  season_id BIGINT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  owner_email TEXT NULL,
  owner_name TEXT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'owner'
    CHECK (role IN ('owner', 'co_owner')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_team_owner_user UNIQUE (user_id, team_id, season_id)
);

ALTER TABLE team_owner_users
  ADD COLUMN IF NOT EXISTS owner_email TEXT;

ALTER TABLE team_owner_users
  ADD COLUMN IF NOT EXISTS owner_name TEXT;

UPDATE team_owner_users
SET role = 'co_owner'
WHERE role NOT IN ('owner', 'co_owner');

ALTER TABLE team_owner_users
  DROP CONSTRAINT IF EXISTS team_owner_users_role_check;

ALTER TABLE team_owner_users
  ADD CONSTRAINT team_owner_users_role_check
  CHECK (role IN ('owner', 'co_owner'));

CREATE INDEX IF NOT EXISTS ix_team_owner_users_team
  ON team_owner_users (team_id, season_id, active);

DROP VIEW IF EXISTS public_team_owner_assignments;

CREATE OR REPLACE VIEW public_team_owner_assignments
WITH (security_invoker = true) AS
SELECT
  tou.id,
  tou.user_id,
  COALESCE(tou.owner_email, up.email) AS owner_email,
  COALESCE(tou.owner_name, up.display_name) AS owner_name,
  up.username,
  tou.team_id,
  t.name AS team_name,
  tou.season_id,
  s.season_number,
  s.name AS season_name,
  tou.role,
  tou.active,
  tou.created_at
FROM team_owner_users tou
JOIN teams t ON t.id = tou.team_id
LEFT JOIN user_profiles up ON up.user_id = tou.user_id
LEFT JOIN seasons s ON s.id = tou.season_id;

CREATE TABLE IF NOT EXISTS roster_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  league_code VARCHAR(20) NOT NULL,
  player_id BIGINT NOT NULL REFERENCES mlb_players(id) ON DELETE CASCADE,
  acquired_on DATE NOT NULL DEFAULT CURRENT_DATE,
  released_on DATE NULL,
  contract_years TEXT NULL,
  acquisition_type VARCHAR(20) NOT NULL DEFAULT 'draft'
    CHECK (acquisition_type IN ('draft', 'add', 'trade', 'admin')),
  release_type VARCHAR(20) NULL
    CHECK (release_type IN ('drop', 'trade', 'admin')),
  created_by UUID NULL REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_roster_dates CHECK (released_on IS NULL OR released_on >= acquired_on)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_active_player_claim_by_league
  ON roster_memberships (season_id, league_code, player_id)
  WHERE released_on IS NULL;

CREATE INDEX IF NOT EXISTS ix_roster_memberships_team
  ON roster_memberships (season_id, team_id, released_on);

ALTER TABLE roster_memberships
  ADD COLUMN IF NOT EXISTS contract_years TEXT;

CREATE TABLE IF NOT EXISTS roster_periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  week_number INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  lineup_lock_at TIMESTAMP WITH TIME ZONE NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'locked', 'scoring', 'final')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_roster_period UNIQUE (season_id, week_number),
  CONSTRAINT chk_roster_period_dates CHECK (ends_on >= starts_on)
);

CREATE TABLE IF NOT EXISTS lineup_slots (
  code VARCHAR(10) PRIMARY KEY,
  label VARCHAR(40) NOT NULL,
  player_group VARCHAR(10) NOT NULL CHECK (player_group IN ('hitter', 'pitcher')),
  allowed_positions TEXT[] NOT NULL,
  sort_order INT NOT NULL
);

INSERT INTO lineup_slots (code, label, player_group, allowed_positions, sort_order)
VALUES
  ('C', 'Catcher', 'hitter', ARRAY['C'], 10),
  ('1B', 'First Base', 'hitter', ARRAY['1B'], 20),
  ('2B', 'Second Base', 'hitter', ARRAY['2B'], 30),
  ('SS', 'Shortstop', 'hitter', ARRAY['SS'], 40),
  ('3B', 'Third Base', 'hitter', ARRAY['3B'], 50),
  ('OF1', 'Outfield', 'hitter', ARRAY['OF', 'LF', 'CF', 'RF'], 60),
  ('OF2', 'Outfield', 'hitter', ARRAY['OF', 'LF', 'CF', 'RF'], 70),
  ('OF3', 'Outfield', 'hitter', ARRAY['OF', 'LF', 'CF', 'RF'], 80),
  ('DH', 'Designated Hitter', 'hitter', ARRAY['C', '1B', '2B', 'SS', '3B', 'OF', 'LF', 'CF', 'RF', 'DH'], 90),
  ('SP1', 'Starting Pitcher', 'pitcher', ARRAY['SP'], 100),
  ('SP2', 'Starting Pitcher', 'pitcher', ARRAY['SP'], 110),
  ('SP3', 'Starting Pitcher', 'pitcher', ARRAY['SP'], 120),
  ('SP4', 'Starting Pitcher', 'pitcher', ARRAY['SP'], 130),
  ('RP1', 'Relief Pitcher', 'pitcher', ARRAY['RP'], 140),
  ('RP2', 'Relief Pitcher', 'pitcher', ARRAY['RP'], 150)
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label,
  player_group = EXCLUDED.player_group,
  allowed_positions = EXCLUDED.allowed_positions,
  sort_order = EXCLUDED.sort_order;

CREATE TABLE IF NOT EXISTS team_lineup_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id BIGINT NOT NULL REFERENCES roster_periods(id) ON DELETE CASCADE,
  team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  player_id BIGINT NOT NULL REFERENCES mlb_players(id) ON DELETE CASCADE,
  slot_code VARCHAR(10) NOT NULL REFERENCES lineup_slots(code),
  locked BOOLEAN NOT NULL DEFAULT FALSE,
  updated_by UUID NULL REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_team_lineup_slot UNIQUE (period_id, team_id, slot_code),
  CONSTRAINT uq_team_lineup_player UNIQUE (period_id, team_id, player_id)
);

CREATE TABLE IF NOT EXISTS roster_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  league_code VARCHAR(20) NOT NULL,
  transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('add', 'drop', 'trade', 'lineup', 'admin')),
  player_id BIGINT NULL REFERENCES mlb_players(id),
  related_player_id BIGINT NULL REFERENCES mlb_players(id),
  notes TEXT NULL,
  created_by UUID NULL REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_roster_transactions_team
  ON roster_transactions (season_id, team_id, created_at DESC);

CREATE TABLE IF NOT EXISTS scoring_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  player_group VARCHAR(10) NOT NULL CHECK (player_group IN ('hitter', 'pitcher')),
  stat_code VARCHAR(20) NOT NULL,
  stat_name VARCHAR(120) NOT NULL,
  points NUMERIC(8,2) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_scoring_rule UNIQUE (season_id, player_group, stat_code)
);

DELETE FROM scoring_rules
WHERE season_id IS NULL;

INSERT INTO scoring_rules (season_id, player_group, stat_code, stat_name, points, sort_order)
VALUES
  (NULL, 'hitter', 'R', 'Runs', 1, 10),
  (NULL, 'hitter', '1B', 'Singles', 1, 20),
  (NULL, 'hitter', '2B', 'Doubles', 3, 30),
  (NULL, 'hitter', '3B', 'Triples', 4, 40),
  (NULL, 'hitter', 'HR', 'Home Runs', 4, 50),
  (NULL, 'hitter', 'RBI', 'Runs Batted In', 1, 60),
  (NULL, 'hitter', 'SB', 'Stolen Bases', 2, 70),
  (NULL, 'hitter', 'CS', 'Caught Stealing', -1, 80),
  (NULL, 'hitter', 'BB', 'Walks', 1, 90),
  (NULL, 'hitter', 'HBP', 'Hit By Pitch', 1, 100),
  (NULL, 'hitter', 'GIDP', 'Ground Into Double Play', -2, 110),
  (NULL, 'hitter', 'CYC', 'Hitting For The Cycle', 5, 120),
  (NULL, 'hitter', 'SLAM', 'Grand Slam Home Runs', 2, 130),
  (NULL, 'pitcher', 'IP', 'Innings Pitched', 1, 210),
  (NULL, 'pitcher', 'W', 'Wins', 4, 220),
  (NULL, 'pitcher', 'L', 'Losses', -2, 230),
  (NULL, 'pitcher', 'CG', 'Complete Games', 2, 240),
  (NULL, 'pitcher', 'SHO', 'Shutouts', 5, 250),
  (NULL, 'pitcher', 'SV', 'Saves', 5, 260),
  (NULL, 'pitcher', 'K', 'Strikeouts', 1, 270),
  (NULL, 'pitcher', 'HLD', 'Holds', 4, 280),
  (NULL, 'pitcher', 'RAPP', 'Relief Appearances', 1, 290),
  (NULL, 'pitcher', 'NH', 'No Hitters', 5, 300),
  (NULL, 'pitcher', 'PG', 'Perfect Games', 5, 310),
  (NULL, 'pitcher', 'QS', 'Quality Starts', 3, 320),
  (NULL, 'pitcher', 'BSV', 'Blown Saves', -1, 330);

CREATE TABLE IF NOT EXISTS mlb_player_daily_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES mlb_players(id) ON DELETE CASCADE,
  stat_date DATE NOT NULL,
  mlb_team_id BIGINT NULL REFERENCES mlb_teams(id),
  stats JSONB NOT NULL DEFAULT '{}'::jsonb,
  imported_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_mlb_player_daily_stats UNIQUE (player_id, stat_date)
);

CREATE TABLE IF NOT EXISTS fantasy_player_daily_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id BIGINT NOT NULL REFERENCES roster_periods(id) ON DELETE CASCADE,
  team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  player_id BIGINT NOT NULL REFERENCES mlb_players(id) ON DELETE CASCADE,
  slot_code VARCHAR(10) NOT NULL REFERENCES lineup_slots(code),
  stat_date DATE NOT NULL,
  points NUMERIC(10,2) NOT NULL DEFAULT 0,
  scoring_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_fantasy_player_daily_score UNIQUE (period_id, team_id, player_id, stat_date)
);

CREATE OR REPLACE FUNCTION is_admin_user()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM admin_users au
    WHERE au.user_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION is_commissioner_user()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
AS $$
  SELECT public.is_commissioner_user(auth.uid());
$$;

CREATE OR REPLACE FUNCTION owns_team(target_team_id BIGINT, target_season_id BIGINT DEFAULT NULL)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM team_owner_users tou
    WHERE tou.user_id = auth.uid()
      AND tou.team_id = target_team_id
      AND tou.active = TRUE
      AND tou.role IN ('owner', 'co_owner')
      AND (tou.season_id IS NULL OR target_season_id IS NULL OR tou.season_id = target_season_id)
  );
$$;

CREATE OR REPLACE FUNCTION public.can_view_league_rosters(target_season_id BIGINT, target_league_code TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    public.is_admin_user(auth.uid())
    OR EXISTS (
      SELECT 1
      FROM team_owner_users tou
      JOIN season_team_assignments sta
        ON sta.team_id = tou.team_id
        AND sta.season_id = target_season_id
      WHERE tou.user_id = auth.uid()
        AND tou.active = TRUE
        AND tou.role IN ('owner', 'co_owner')
        AND lower(sta.league_code) = lower(target_league_code)
        AND (tou.season_id IS NULL OR tou.season_id = target_season_id)
    );
$$;

GRANT EXECUTE ON FUNCTION public.can_view_league_rosters(BIGINT, TEXT) TO authenticated;

CREATE OR REPLACE VIEW public_available_players AS
SELECT
  sta.season_id,
  sta.league_code,
  p.id AS player_id,
  p.mlb_player_id,
  p.display_name,
  p.primary_position,
  p.eligible_positions,
  mt.abbreviation AS mlb_team_abbreviation
FROM season_team_assignments sta
CROSS JOIN mlb_players p
LEFT JOIN mlb_teams mt ON mt.id = p.mlb_team_id
WHERE p.active = TRUE
  AND NOT EXISTS (
    SELECT 1
    FROM roster_memberships rm
    WHERE rm.season_id = sta.season_id
      AND rm.league_code = sta.league_code
      AND rm.player_id = p.id
      AND rm.released_on IS NULL
  )
GROUP BY
  sta.season_id,
  sta.league_code,
  p.id,
  p.mlb_player_id,
  p.display_name,
  p.primary_position,
  p.eligible_positions,
  mt.abbreviation;

DROP VIEW IF EXISTS public_team_rosters;

CREATE OR REPLACE VIEW public_team_rosters
WITH (security_invoker = true) AS
SELECT
  rm.season_id,
  s.season_number,
  rm.league_code,
  rm.team_id,
  t.name AS team_name,
  rm.player_id,
  p.mlb_player_id,
  p.display_name AS player_name,
  p.primary_position,
  p.eligible_positions,
  mt.abbreviation AS mlb_team_abbreviation,
  rm.acquired_on,
  rm.contract_years,
  rm.acquisition_type
FROM roster_memberships rm
JOIN seasons s ON s.id = rm.season_id
JOIN teams t ON t.id = rm.team_id
JOIN mlb_players p ON p.id = rm.player_id
LEFT JOIN mlb_teams mt ON mt.id = p.mlb_team_id
WHERE rm.released_on IS NULL
  AND public.can_view_league_rosters(rm.season_id, rm.league_code);

ALTER TABLE team_owner_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE roster_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE roster_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_lineup_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE roster_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE scoring_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE mlb_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE mlb_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE mlb_player_daily_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE fantasy_player_daily_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read MLB teams" ON mlb_teams;
CREATE POLICY "Public can read MLB teams"
ON mlb_teams FOR SELECT TO anon, authenticated USING (TRUE);

DROP POLICY IF EXISTS "Public can read MLB players" ON mlb_players;
CREATE POLICY "Public can read MLB players"
ON mlb_players FOR SELECT TO anon, authenticated USING (TRUE);

DROP POLICY IF EXISTS "Public can read scoring rules" ON scoring_rules;
CREATE POLICY "Public can read scoring rules"
ON scoring_rules FOR SELECT TO anon, authenticated USING (active = TRUE);

DROP POLICY IF EXISTS "Public can read roster periods" ON roster_periods;
CREATE POLICY "Public can read roster periods"
ON roster_periods FOR SELECT TO anon, authenticated USING (TRUE);

DROP POLICY IF EXISTS "Owners can read team owner rows" ON team_owner_users;
CREATE POLICY "Owners can read team owner rows"
ON team_owner_users FOR SELECT TO authenticated
USING (user_id = auth.uid() OR is_admin_user());

DROP POLICY IF EXISTS "Admins can manage team owner rows" ON team_owner_users;
CREATE POLICY "Admins can manage team owner rows"
ON team_owner_users FOR ALL TO authenticated
USING (is_admin_user())
WITH CHECK (is_admin_user());

DROP POLICY IF EXISTS "Public can read active rosters" ON roster_memberships;
DROP POLICY IF EXISTS "Authenticated league owners can read active rosters" ON roster_memberships;
CREATE POLICY "Authenticated league owners can read active rosters"
ON roster_memberships FOR SELECT TO authenticated
USING (
  released_on IS NULL
  AND public.can_view_league_rosters(season_id, league_code)
);

DROP POLICY IF EXISTS "Owners can claim players" ON roster_memberships;
CREATE POLICY "Owners can claim players"
ON roster_memberships FOR INSERT TO authenticated
WITH CHECK (owns_team(team_id, season_id) OR is_commissioner_user());

DROP POLICY IF EXISTS "Owners can update their roster" ON roster_memberships;
CREATE POLICY "Owners can update their roster"
ON roster_memberships FOR UPDATE TO authenticated
USING (owns_team(team_id, season_id) OR is_commissioner_user())
WITH CHECK (owns_team(team_id, season_id) OR is_commissioner_user());

DROP POLICY IF EXISTS "Public can read lineups" ON team_lineup_entries;
CREATE POLICY "Public can read lineups"
ON team_lineup_entries FOR SELECT TO anon, authenticated
USING (TRUE);

DROP POLICY IF EXISTS "Owners can set lineups" ON team_lineup_entries;
CREATE POLICY "Owners can set lineups"
ON team_lineup_entries FOR INSERT TO authenticated
WITH CHECK (
  owns_team(team_id, (SELECT rp.season_id FROM roster_periods rp WHERE rp.id = period_id))
  OR is_commissioner_user()
);

DROP POLICY IF EXISTS "Owners can update lineups" ON team_lineup_entries;
CREATE POLICY "Owners can update lineups"
ON team_lineup_entries FOR UPDATE TO authenticated
USING (
  owns_team(team_id, (SELECT rp.season_id FROM roster_periods rp WHERE rp.id = period_id))
  OR is_commissioner_user()
)
WITH CHECK (
  owns_team(team_id, (SELECT rp.season_id FROM roster_periods rp WHERE rp.id = period_id))
  OR is_commissioner_user()
);

DROP POLICY IF EXISTS "Owners can delete lineup entries" ON team_lineup_entries;
CREATE POLICY "Owners can delete lineup entries"
ON team_lineup_entries FOR DELETE TO authenticated
USING (
  owns_team(team_id, (SELECT rp.season_id FROM roster_periods rp WHERE rp.id = period_id))
  OR is_commissioner_user()
);

DROP POLICY IF EXISTS "Owners can read transactions" ON roster_transactions;
CREATE POLICY "Owners can read transactions"
ON roster_transactions FOR SELECT TO authenticated
USING (owns_team(team_id, season_id) OR is_commissioner_user());

DROP POLICY IF EXISTS "Owners can write transactions" ON roster_transactions;
CREATE POLICY "Owners can write transactions"
ON roster_transactions FOR INSERT TO authenticated
WITH CHECK (owns_team(team_id, season_id) OR is_commissioner_user());

DROP POLICY IF EXISTS "Admins can manage scoring rules" ON scoring_rules;
CREATE POLICY "Admins can manage scoring rules"
ON scoring_rules FOR ALL TO authenticated
USING (is_admin_user())
WITH CHECK (is_admin_user());

DROP POLICY IF EXISTS "Admins can manage MLB teams" ON mlb_teams;
CREATE POLICY "Admins can manage MLB teams"
ON mlb_teams FOR ALL TO authenticated
USING (is_admin_user())
WITH CHECK (is_admin_user());

DROP POLICY IF EXISTS "Admins can manage MLB players" ON mlb_players;
CREATE POLICY "Admins can manage MLB players"
ON mlb_players FOR ALL TO authenticated
USING (is_admin_user())
WITH CHECK (is_admin_user());

DROP POLICY IF EXISTS "Admins can manage imported MLB stats" ON mlb_player_daily_stats;
CREATE POLICY "Admins can manage imported MLB stats"
ON mlb_player_daily_stats FOR ALL TO authenticated
USING (is_admin_user())
WITH CHECK (is_admin_user());

DROP POLICY IF EXISTS "Public can read fantasy player daily scores" ON fantasy_player_daily_scores;
CREATE POLICY "Public can read fantasy player daily scores"
ON fantasy_player_daily_scores FOR SELECT TO anon, authenticated
USING (TRUE);

DROP POLICY IF EXISTS "Admins can manage fantasy player daily scores" ON fantasy_player_daily_scores;
CREATE POLICY "Admins can manage fantasy player daily scores"
ON fantasy_player_daily_scores FOR ALL TO authenticated
USING (is_admin_user())
WITH CHECK (is_admin_user());

GRANT SELECT ON public_available_players TO anon, authenticated;
REVOKE SELECT ON public_team_rosters FROM anon;
GRANT SELECT ON public_team_rosters TO authenticated;
GRANT SELECT ON public_team_owner_assignments TO authenticated;
