-- Run this in Supabase SQL Editor before public_views.sql.
-- This file mirrors ../season28_normalized_schema_postgres.sql.

CREATE TABLE seasons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_number INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'planned'
    CHECK (status IN ('planned', 'active', 'complete', 'archived')),
  starts_on DATE NULL,
  ends_on DATE NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_seasons_number UNIQUE (season_number)
);

CREATE TABLE teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  city VARCHAR(120) NULL,
  nickname VARCHAR(120) NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_teams_name UNIQUE (name)
);

CREATE TABLE team_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES teams(id),
  alias VARCHAR(160) NOT NULL,
  source_name VARCHAR(80) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_team_aliases_alias UNIQUE (alias)
);

CREATE TABLE season_team_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NOT NULL REFERENCES seasons(id),
  team_id BIGINT NOT NULL REFERENCES teams(id),
  league_code VARCHAR(20) NOT NULL,
  conference_code VARCHAR(20) NOT NULL,
  division_code VARCHAR(20) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_season_team UNIQUE (season_id, team_id)
);

CREATE INDEX ix_season_alignment
  ON season_team_assignments (season_id, league_code, conference_code, division_code);

CREATE TABLE standings_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NOT NULL REFERENCES seasons(id),
  label VARCHAR(120) NOT NULL,
  source_file VARCHAR(255) NULL,
  source_sheet VARCHAR(80) NULL,
  snapshot_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_current BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_standings_snapshots_current
  ON standings_snapshots (season_id, is_current);

CREATE TABLE standings_rows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL REFERENCES standings_snapshots(id),
  season_team_assignment_id BIGINT NOT NULL REFERENCES season_team_assignments(id),
  offense_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  pitching_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  wins INT NOT NULL DEFAULT 0,
  losses INT NOT NULL DEFAULT 0,
  win_pct NUMERIC(7,5) NOT NULL DEFAULT 0.00000,
  rank_in_group INT NULL,
  plus_minus NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  pct_to_average NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  division_wins INT NOT NULL DEFAULT 0,
  division_losses INT NOT NULL DEFAULT 0,
  conference_wins INT NOT NULL DEFAULT 0,
  conference_losses INT NOT NULL DEFAULT 0,
  average_per_week NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  raw_row_number INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_standings_snapshot_team UNIQUE (snapshot_id, season_team_assignment_id)
);

CREATE TABLE team_schedule_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_team_assignment_id BIGINT NOT NULL REFERENCES season_team_assignments(id),
  slot_number INT NOT NULL,
  opponent_slot INT NULL,
  home_away CHAR(1) NULL CHECK (home_away IN ('H', 'A')),
  raw_value VARCHAR(20) NULL,
  CONSTRAINT uq_team_schedule_slot UNIQUE (season_team_assignment_id, slot_number)
);

CREATE TABLE games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id BIGINT NOT NULL REFERENCES seasons(id),
  game_number INT NOT NULL,
  matchup_number INT NOT NULL,
  league_code VARCHAR(20) NOT NULL,
  at_code VARCHAR(20) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'final'
    CHECK (status IN ('scheduled', 'in_progress', 'final', 'cancelled')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_games_natural UNIQUE (season_id, game_number, matchup_number, league_code, at_code)
);

CREATE TABLE game_team_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES games(id),
  team_id BIGINT NOT NULL REFERENCES teams(id),
  result CHAR(1) NULL CHECK (result IN ('W', 'L', 'T', 'N')),
  score NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  lead_margin NUMERIC(10,2) NULL,
  offense_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  pitching_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  infield_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  outfield_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  dh_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  starting_pitching_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  relief_pitching_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  psr NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  home_away CHAR(1) NOT NULL CHECK (home_away IN ('H', 'A')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_game_team_results UNIQUE (game_id, team_id)
);

CREATE TABLE positions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  name VARCHAR(80) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT uq_positions_code UNIQUE (code)
);

CREATE TABLE players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR(160) NOT NULL,
  normalized_name VARCHAR(160) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_players_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE player_game_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES games(id),
  team_id BIGINT NOT NULL REFERENCES teams(id),
  player_id BIGINT NOT NULL REFERENCES players(id),
  position_id BIGINT NOT NULL REFERENCES positions(id),
  position_sort INT NULL,
  category_primary VARCHAR(20) NULL,
  category_secondary VARCHAR(20) NULL,
  home_away CHAR(1) NOT NULL CHECK (home_away IN ('H', 'A')),
  monday_points NUMERIC(10,2) NULL,
  tuesday_points NUMERIC(10,2) NULL,
  wednesday_points NUMERIC(10,2) NULL,
  thursday_points NUMERIC(10,2) NULL,
  friday_points NUMERIC(10,2) NULL,
  saturday_points NUMERIC(10,2) NULL,
  sunday_points NUMERIC(10,2) NULL,
  total_points NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  raw_row_number INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_player_game_lines_player
  ON player_game_lines (player_id);

CREATE INDEX ix_player_game_lines_team_game
  ON player_game_lines (team_id, game_id);
