-- Generated from Rosters Keystone.xlsx.
-- Season 32 Keystone roster snapshot.
-- Player rows: 475.
-- Team counts: ALBATROSSES: 30, APOCALYPSE: 30, BOMBERS: 28, COBRAS: 29, DIABLOS: 29, HACKERS: 30, HERMANOS: 30, HIGHLANDERS: 29, HOPHEADS: 30, LEOPARDS: 30, PEREGRINES: 30, RAIDERS: 30, ROGUES: 30, SLAYERS: 30, SPIDERS: 30, VIXENS: 30
-- Yahoo status counts: ACTIVE: 395, DTD: 7, IL10: 24, IL15: 16, IL60: 21, NA: 12
-- Run after supabase/seed_teams.sql and supabase/roster_management.sql.

BEGIN;

INSERT INTO mlb_teams (abbreviation, name, active)
VALUES
  ('ATH', 'Athletics', TRUE),
  ('ATL', 'Atlanta Braves', TRUE),
  ('AZ', 'Arizona Diamondbacks', TRUE),
  ('BAL', 'Baltimore Orioles', TRUE),
  ('BOS', 'Boston Red Sox', TRUE),
  ('CHC', 'Chicago Cubs', TRUE),
  ('CIN', 'Cincinnati Reds', TRUE),
  ('CLE', 'Cleveland Guardians', TRUE),
  ('COL', 'Colorado Rockies', TRUE),
  ('CWS', 'Chicago White Sox', TRUE),
  ('DET', 'Detroit Tigers', TRUE),
  ('HOU', 'Houston Astros', TRUE),
  ('KC', 'Kansas City Royals', TRUE),
  ('LAA', 'Los Angeles Angels', TRUE),
  ('LAD', 'Los Angeles Dodgers', TRUE),
  ('MIA', 'Miami Marlins', TRUE),
  ('MIL', 'Milwaukee Brewers', TRUE),
  ('MIN', 'Minnesota Twins', TRUE),
  ('NYM', 'New York Mets', TRUE),
  ('NYY', 'New York Yankees', TRUE),
  ('PHI', 'Philadelphia Phillies', TRUE),
  ('PIT', 'Pittsburgh Pirates', TRUE),
  ('SD', 'San Diego Padres', TRUE),
  ('SEA', 'Seattle Mariners', TRUE),
  ('SF', 'San Francisco Giants', TRUE),
  ('STL', 'St. Louis Cardinals', TRUE),
  ('TB', 'Tampa Bay Rays', TRUE),
  ('TEX', 'Texas Rangers', TRUE),
  ('TOR', 'Toronto Blue Jays', TRUE),
  ('WSH', 'Washington Nationals', TRUE)
ON CONFLICT (abbreviation) DO UPDATE SET
  name = EXCLUDED.name,
  active = TRUE,
  updated_at = NOW();

WITH player_seed (
  display_name,
  normalized_name,
  mlb_abbreviation,
  primary_position,
  eligible_positions
) AS (
  VALUES
  ('A.J. Ewing', 'a j ewing', 'NYM', '2B', ARRAY['2B', 'OF']::text[]),
  ('Aaron Ashby', 'aaron ashby', 'MIL', 'RP', ARRAY['RP']::text[]),
  ('Aaron Judge', 'aaron judge', 'NYY', 'OF', ARRAY['OF']::text[]),
  ('Aaron Nola', 'aaron nola', 'PHI', 'SP', ARRAY['SP']::text[]),
  ('Abner Uribe', 'abner uribe', 'MIL', 'RP', ARRAY['RP']::text[]),
  ('Addison Barger', 'addison barger', 'TOR', '3B', ARRAY['3B', 'OF']::text[]),
  ('Adley Rutschman', 'adley rutschman', 'BAL', 'C', ARRAY['C']::text[]),
  ('Adrian Morejon', 'adrian morejon', 'SD', 'RP', ARRAY['RP']::text[]),
  ('Agustín Ramírez', 'agustin ramirez', 'MIA', 'C', ARRAY['C']::text[]),
  ('AJ Smith-Shawver', 'aj smith shawver', 'ATL', 'SP', ARRAY['SP']::text[]),
  ('Alec Bohm', 'alec bohm', 'PHI', '1B', ARRAY['1B', '3B']::text[]),
  ('Alec Burleson', 'alec burleson', 'STL', '1B', ARRAY['1B', 'OF']::text[]),
  ('Alejandro Kirk', 'alejandro kirk', 'TOR', 'C', ARRAY['C']::text[]),
  ('Alex Bregman', 'alex bregman', 'CHC', '3B', ARRAY['3B']::text[]),
  ('Alex Lange', 'alex lange', 'KC', 'RP', ARRAY['RP']::text[]),
  ('Alex Vesia', 'alex vesia', 'LAD', 'RP', ARRAY['RP']::text[]),
  ('Andre Pallante', 'andre pallante', 'STL', 'SP', ARRAY['SP']::text[]),
  ('Andrés Giménez', 'andres gimenez', 'TOR', '2B', ARRAY['2B', 'SS']::text[]),
  ('Andrés Muñoz', 'andres munoz', 'SEA', 'RP', ARRAY['RP']::text[]),
  ('Andrew Abbott', 'andrew abbott', 'CIN', 'SP', ARRAY['SP']::text[]),
  ('Andrew Benintendi', 'andrew benintendi', 'CWS', 'OF', ARRAY['OF']::text[]),
  ('Andrew Kittredge', 'andrew kittredge', 'BAL', 'RP', ARRAY['RP']::text[]),
  ('Andrew Vaughn', 'andrew vaughn', 'MIL', '1B', ARRAY['1B']::text[]),
  ('Andy Pages', 'andy pages', 'LAD', 'OF', ARRAY['OF']::text[]),
  ('Angel Martínez', 'angel martinez', 'CLE', '2B', ARRAY['2B', 'OF']::text[]),
  ('Anthony Seigler', 'anthony seigler', 'BOS', '2B', ARRAY['2B', '3B']::text[]),
  ('Anthony Volpe', 'anthony volpe', 'NYY', 'SS', ARRAY['SS']::text[]),
  ('Antonio Senzatela', 'antonio senzatela', 'COL', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Aroldis Chapman', 'aroldis chapman', 'BOS', 'RP', ARRAY['RP']::text[]),
  ('Austin Martin', 'austin martin', 'MIN', '2B', ARRAY['2B', 'OF']::text[]),
  ('Austin Riley', 'austin riley', 'ATL', '3B', ARRAY['3B']::text[]),
  ('Austin Wells', 'austin wells', 'NYY', 'C', ARRAY['C']::text[]),
  ('Bailey Ober', 'bailey ober', 'MIN', 'SP', ARRAY['SP']::text[]),
  ('Ben Brown', 'ben brown', 'CHC', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Ben Joyce', 'ben joyce', 'LAA', 'RP', ARRAY['RP']::text[]),
  ('Ben Rice', 'ben rice', 'NYY', 'C', ARRAY['C', '1B']::text[]),
  ('Blake Snell', 'blake snell', 'LAD', 'SP', ARRAY['SP']::text[]),
  ('Blaze Alexander', 'blaze alexander', 'BAL', '2B', ARRAY['2B', '3B', 'SS', 'OF']::text[]),
  ('Blaze Jordan', 'blaze jordan', 'STL', '1B', ARRAY['1B', '3B']::text[]),
  ('Bo Bichette', 'bo bichette', 'NYM', '3B', ARRAY['3B', 'SS']::text[]),
  ('Bobby Witt Jr.', 'bobby witt jr', 'KC', 'SS', ARRAY['SS']::text[]),
  ('Brad Keller', 'brad keller', 'PHI', 'RP', ARRAY['RP']::text[]),
  ('Braden Montgomery', 'braden montgomery', 'CWS', 'OF', ARRAY['OF']::text[]),
  ('Brady Singer', 'brady singer', 'CIN', 'SP', ARRAY['SP']::text[]),
  ('Brandon Lowe', 'brandon lowe', 'PIT', '2B', ARRAY['2B']::text[]),
  ('Brandon Marsh', 'brandon marsh', 'PHI', 'OF', ARRAY['OF']::text[]),
  ('Brandon Nimmo', 'brandon nimmo', 'TEX', 'OF', ARRAY['OF']::text[]),
  ('Brandon Pfaadt', 'brandon pfaadt', 'AZ', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Brandon Valenzuela', 'brandon valenzuela', 'TOR', 'C', ARRAY['C', '1B']::text[]),
  ('Brandon Young', 'brandon young', 'BAL', 'SP', ARRAY['SP']::text[]),
  ('Braxton Ashcraft', 'braxton ashcraft', 'PIT', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Brayan Rocchio', 'brayan rocchio', 'CLE', '2B', ARRAY['2B', 'SS']::text[]),
  ('Brendan Donovan', 'brendan donovan', 'SEA', '2B', ARRAY['2B', '3B', 'SS', 'OF']::text[]),
  ('Brett Baty', 'brett baty', 'NYM', '1B', ARRAY['1B', '2B', '3B', 'OF']::text[]),
  ('Brice Turang', 'brice turang', 'MIL', '2B', ARRAY['2B']::text[]),
  ('Brooks Lee', 'brooks lee', 'MIN', '2B', ARRAY['2B', '3B', 'SS']::text[]),
  ('Bryan Abreu', 'bryan abreu', 'HOU', 'RP', ARRAY['RP']::text[]),
  ('Bryan Baker', 'bryan baker', 'TB', 'RP', ARRAY['RP']::text[]),
  ('Bryan King', 'bryan king', 'HOU', 'RP', ARRAY['RP']::text[]),
  ('Bryan Reynolds', 'bryan reynolds', 'PIT', 'OF', ARRAY['OF']::text[]),
  ('Bryan Woo', 'bryan woo', 'SEA', 'SP', ARRAY['SP']::text[]),
  ('Bryce Elder', 'bryce elder', 'ATL', 'SP', ARRAY['SP']::text[]),
  ('Bryce Eldridge', 'bryce eldridge', 'SF', '1B', ARRAY['1B']::text[]),
  ('Bryce Harper', 'bryce harper', 'PHI', '1B', ARRAY['1B']::text[]),
  ('Bryce Miller', 'bryce miller', 'SEA', 'SP', ARRAY['SP']::text[]),
  ('Bryson Stott', 'bryson stott', 'PHI', '2B', ARRAY['2B', 'SS']::text[]),
  ('Bubba Chandler', 'bubba chandler', 'PIT', 'SP', ARRAY['SP']::text[]),
  ('Byron Buxton', 'byron buxton', 'MIN', 'OF', ARRAY['OF']::text[]),
  ('Cade Cavalli', 'cade cavalli', 'WSH', 'SP', ARRAY['SP']::text[]),
  ('Cade Smith', 'cade smith', 'CLE', 'RP', ARRAY['RP']::text[]),
  ('Cal Raleigh', 'cal raleigh', 'SEA', 'C', ARRAY['C']::text[]),
  ('Caleb Durbin', 'caleb durbin', 'BOS', '2B', ARRAY['2B', '3B']::text[]),
  ('Cam Schlittler', 'cam schlittler', 'NYY', 'SP', ARRAY['SP']::text[]),
  ('Cam Smith', 'cam smith', 'HOU', 'OF', ARRAY['OF']::text[]),
  ('Camilo Doval', 'camilo doval', 'NYY', 'RP', ARRAY['RP']::text[]),
  ('Carlos Lagrange', 'carlos lagrange', 'NYY', 'SP', ARRAY['SP']::text[]),
  ('Carlos Rodón', 'carlos rodon', 'NYY', 'SP', ARRAY['SP']::text[]),
  ('Carson Benge', 'carson benge', 'NYM', 'OF', ARRAY['OF']::text[]),
  ('Carson Kelly', 'carson kelly', 'CHC', 'C', ARRAY['C']::text[]),
  ('Carter Jensen', 'carter jensen', 'KC', 'C', ARRAY['C']::text[]),
  ('Casey Mize', 'casey mize', 'DET', 'SP', ARRAY['SP']::text[]),
  ('Casey Schmitt', 'casey schmitt', 'SF', '1B', ARRAY['1B', '2B', '3B', 'OF']::text[]),
  ('Ceddanne Rafaela', 'ceddanne rafaela', 'BOS', '2B', ARRAY['2B', 'OF']::text[]),
  ('Cedric Mullins', 'cedric mullins', 'TB', 'OF', ARRAY['OF']::text[]),
  ('Chandler Simpson', 'chandler simpson', 'TB', 'OF', ARRAY['OF']::text[]),
  ('Charlie Condon', 'charlie condon', 'COL', '1B', ARRAY['1B', 'OF']::text[]),
  ('Chase Burns', 'chase burns', 'CIN', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Chase DeLauter', 'chase delauter', 'CLE', 'OF', ARRAY['OF']::text[]),
  ('Chase Meidroth', 'chase meidroth', 'CWS', '2B', ARRAY['2B', '3B', 'SS']::text[]),
  ('Chris Bassitt', 'chris bassitt', 'BAL', 'SP', ARRAY['SP']::text[]),
  ('Chris Sale', 'chris sale', 'ATL', 'SP', ARRAY['SP']::text[]),
  ('Christian Scott', 'christian scott', 'NYM', 'SP', ARRAY['SP']::text[]),
  ('Christian Walker', 'christian walker', 'HOU', '1B', ARRAY['1B']::text[]),
  ('Christian Yelich', 'christian yelich', 'MIL', 'OF', ARRAY['OF']::text[]),
  ('CJ Abrams', 'cj abrams', 'WSH', 'SS', ARRAY['SS']::text[]),
  ('Clay Holmes', 'clay holmes', 'NYM', 'SP', ARRAY['SP']::text[]),
  ('Cody Bellinger', 'cody bellinger', 'NYY', 'OF', ARRAY['OF']::text[]),
  ('Cole Carrigg', 'cole carrigg', 'COL', 'OF', ARRAY['OF']::text[]),
  ('Cole Young', 'cole young', 'SEA', '2B', ARRAY['2B']::text[]),
  ('Colin Rea', 'colin rea', 'CHC', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Colson Montgomery', 'colson montgomery', 'CWS', '3B', ARRAY['3B', 'SS']::text[]),
  ('Colt Emerson', 'colt emerson', 'SEA', '3B', ARRAY['3B', 'SS']::text[]),
  ('Colt Keith', 'colt keith', 'DET', '1B', ARRAY['1B', '2B', '3B']::text[]),
  ('Colton Cowser', 'colton cowser', 'BAL', 'OF', ARRAY['OF']::text[]),
  ('Connelly Early', 'connelly early', 'BOS', 'SP', ARRAY['SP']::text[]),
  ('Cooper Pratt', 'cooper pratt', 'MIL', 'SS', ARRAY['SS']::text[]),
  ('Corbin Carroll', 'corbin carroll', 'AZ', 'OF', ARRAY['OF']::text[]),
  ('Corey Seager', 'corey seager', 'TEX', 'SS', ARRAY['SS']::text[]),
  ('Cristopher Sánchez', 'cristopher sanchez', 'PHI', 'SP', ARRAY['SP']::text[]),
  ('Curtis Mead', 'curtis mead', 'WSH', '1B', ARRAY['1B', '2B', '3B']::text[]),
  ('Dalton Rushing', 'dalton rushing', 'LAD', 'C', ARRAY['C']::text[]),
  ('Daniel Palencia', 'daniel palencia', 'CHC', 'RP', ARRAY['RP']::text[]),
  ('Danny Jansen', 'danny jansen', 'TEX', 'C', ARRAY['C']::text[]),
  ('Dansby Swanson', 'dansby swanson', 'CHC', 'SS', ARRAY['SS']::text[]),
  ('Daulton Varsho', 'daulton varsho', 'TOR', 'OF', ARRAY['OF']::text[]),
  ('David Bednar', 'david bednar', 'NYY', 'RP', ARRAY['RP']::text[]),
  ('David Hamilton', 'david hamilton', 'MIL', '2B', ARRAY['2B', '3B', 'SS']::text[]),
  ('David Peterson', 'david peterson', 'CHC', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Davis Martin', 'davis martin', 'CWS', 'SP', ARRAY['SP']::text[]),
  ('Daylen Lile', 'daylen lile', 'WSH', 'OF', ARRAY['OF']::text[]),
  ('Dean Kremer', 'dean kremer', 'BAL', 'SP', ARRAY['SP']::text[]),
  ('Devin Williams', 'devin williams', 'NYM', 'RP', ARRAY['RP']::text[]),
  ('Dillon Dingler', 'dillon dingler', 'DET', 'C', ARRAY['C']::text[]),
  ('Dominic Canzone', 'dominic canzone', 'SEA', 'OF', ARRAY['OF']::text[]),
  ('Drake Baldwin', 'drake baldwin', 'ATL', 'C', ARRAY['C']::text[]),
  ('Drew Rasmussen', 'drew rasmussen', 'TB', 'SP', ARRAY['SP']::text[]),
  ('Dustin May', 'dustin may', 'STL', 'SP', ARRAY['SP']::text[]),
  ('Dylan Cease', 'dylan cease', 'TOR', 'SP', ARRAY['SP']::text[]),
  ('Dylan Crews', 'dylan crews', 'WSH', 'OF', ARRAY['OF']::text[]),
  ('Eduardo Rodriguez', 'eduardo rodriguez', 'AZ', 'SP', ARRAY['SP']::text[]),
  ('Eduardo Valencia', 'eduardo valencia', 'DET', 'C', ARRAY['C', '1B']::text[]),
  ('Edward Cabrera', 'edward cabrera', 'CHC', 'SP', ARRAY['SP']::text[]),
  ('Edwin Díaz', 'edwin diaz', 'LAD', 'RP', ARRAY['RP']::text[]),
  ('Elly De La Cruz', 'elly de la cruz', 'CIN', 'SS', ARRAY['SS']::text[]),
  ('Emerson Hancock', 'emerson hancock', 'SEA', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Emilio Pagán', 'emilio pagan', 'CIN', 'RP', ARRAY['RP']::text[]),
  ('Emmet Sheehan', 'emmet sheehan', 'LAD', 'SP', ARRAY['SP']::text[]),
  ('Ernie Clement', 'ernie clement', 'TOR', '1B', ARRAY['1B', '2B', '3B', 'SS']::text[]),
  ('Esmerlyn Valdez', 'esmerlyn valdez', 'PIT', '1B', ARRAY['1B', 'OF']::text[]),
  ('Eugenio Suárez', 'eugenio suarez', 'CIN', '3B', ARRAY['3B']::text[]),
  ('Eury Pérez', 'eury perez', 'MIA', 'SP', ARRAY['SP']::text[]),
  ('Evan Phillips', 'evan phillips', 'LAD', 'RP', ARRAY['RP']::text[]),
  ('Ezequiel Duran', 'ezequiel duran', 'TEX', '1B', ARRAY['1B', '2B', '3B', 'SS', 'OF']::text[]),
  ('Fernando Cruz', 'fernando cruz', 'NYY', 'RP', ARRAY['RP']::text[]),
  ('Fernando Tatis Jr.', 'fernando tatis jr', 'SD', '2B', ARRAY['2B', 'OF']::text[]),
  ('Foster Griffin', 'foster griffin', 'WSH', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Framber Valdez', 'framber valdez', 'DET', 'SP', ARRAY['SP']::text[]),
  ('Francisco Alvarez', 'francisco alvarez', 'NYM', 'C', ARRAY['C']::text[]),
  ('Francisco Lindor', 'francisco lindor', 'NYM', 'SS', ARRAY['SS']::text[]),
  ('Freddie Freeman', 'freddie freeman', 'LAD', '1B', ARRAY['1B']::text[]),
  ('Freddy Peralta', 'freddy peralta', 'NYM', 'SP', ARRAY['SP']::text[]),
  ('Gabriel Moreno', 'gabriel moreno', 'AZ', 'C', ARRAY['C']::text[]),
  ('Gage Jump', 'gage jump', 'ATH', 'SP', ARRAY['SP']::text[]),
  ('Garrett Cleavinger', 'garrett cleavinger', 'TB', 'RP', ARRAY['RP']::text[]),
  ('Garrett Crochet', 'garrett crochet', 'BOS', 'SP', ARRAY['SP']::text[]),
  ('Garrett Mitchell', 'garrett mitchell', 'MIL', 'OF', ARRAY['OF']::text[]),
  ('Garrett Whitlock', 'garrett whitlock', 'BOS', 'RP', ARRAY['RP']::text[]),
  ('Gary Sánchez', 'gary sanchez', 'MIL', 'C', ARRAY['C']::text[]),
  ('Gavin Sheets', 'gavin sheets', 'SD', '1B', ARRAY['1B', 'OF']::text[]),
  ('Gavin Williams', 'gavin williams', 'CLE', 'SP', ARRAY['SP']::text[]),
  ('George Kirby', 'george kirby', 'SEA', 'SP', ARRAY['SP']::text[]),
  ('George Lombard Jr.', 'george lombard jr', 'NYY', '2B', ARRAY['2B', '3B', 'SS']::text[]),
  ('George Springer', 'george springer', 'TOR', 'OF', ARRAY['OF']::text[]),
  ('Geraldo Perdomo', 'geraldo perdomo', 'AZ', 'SS', ARRAY['SS']::text[]),
  ('Gerrit Cole', 'gerrit cole', 'NYY', 'SP', ARRAY['SP']::text[]),
  ('Gleyber Torres', 'gleyber torres', 'DET', '2B', ARRAY['2B']::text[]),
  ('Grant Holmes', 'grant holmes', 'ATL', 'SP', ARRAY['SP']::text[]),
  ('Grant Taylor', 'grant taylor', 'CWS', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Grayson Rodriguez', 'grayson rodriguez', 'LAA', 'SP', ARRAY['SP']::text[]),
  ('Gregory Soto', 'gregory soto', 'PIT', 'RP', ARRAY['RP']::text[]),
  ('Griffin Canning', 'griffin canning', 'SD', 'SP', ARRAY['SP']::text[]),
  ('Griffin Jax', 'griffin jax', 'TB', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Gunnar Henderson', 'gunnar henderson', 'BAL', 'SS', ARRAY['SS']::text[]),
  ('Ha-Seong Kim', 'ha seong kim', 'ATL', '2B', ARRAY['2B', 'SS']::text[]),
  ('Harry Ford', 'harry ford', 'WSH', 'C', ARRAY['C']::text[]),
  ('Heliot Ramos', 'heliot ramos', 'SF', 'OF', ARRAY['OF']::text[]),
  ('Henry Bolte', 'henry bolte', 'ATH', 'OF', ARRAY['OF']::text[]),
  ('Heriberto Hernández', 'heriberto hernandez', 'MIA', 'OF', ARRAY['OF']::text[]),
  ('Hogan Harris', 'hogan harris', 'ATH', 'RP', ARRAY['RP']::text[]),
  ('Hunter Brown', 'hunter brown', 'HOU', 'SP', ARRAY['SP']::text[]),
  ('Hunter Gaddis', 'hunter gaddis', 'CLE', 'RP', ARRAY['RP']::text[]),
  ('Hunter Goodman', 'hunter goodman', 'COL', 'C', ARRAY['C']::text[]),
  ('Hunter Greene', 'hunter greene', 'CIN', 'SP', ARRAY['SP']::text[]),
  ('Hyeseong Kim', 'hyeseong kim', 'LAD', '2B', ARRAY['2B', 'SS', 'OF']::text[]),
  ('Ian Happ', 'ian happ', 'CHC', 'OF', ARRAY['OF']::text[]),
  ('Ildemaro Vargas', 'ildemaro vargas', 'AZ', '1B', ARRAY['1B', '2B']::text[]),
  ('Isaac Collins', 'isaac collins', 'KC', 'OF', ARRAY['OF']::text[]),
  ('Isaac Paredes', 'isaac paredes', 'HOU', '1B', ARRAY['1B', '3B']::text[]),
  ('Ivan Herrera', 'ivan herrera', 'STL', 'C', ARRAY['C']::text[]),
  ('J.P. Crawford', 'j p crawford', 'SEA', '3B', ARRAY['3B', 'SS']::text[]),
  ('J.T. Ginn', 'j t ginn', 'ATH', 'SP', ARRAY['SP', 'RP']::text[]),
  ('J.T. Realmuto', 'j t realmuto', 'PHI', 'C', ARRAY['C']::text[]),
  ('Jac Caglianone', 'jac caglianone', 'KC', '1B', ARRAY['1B', 'OF']::text[]),
  ('Jack Flaherty', 'jack flaherty', 'DET', 'SP', ARRAY['SP']::text[]),
  ('Jack Perkins', 'jack perkins', 'ATH', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Jackson Chourio', 'jackson chourio', 'MIL', 'OF', ARRAY['OF']::text[]),
  ('Jackson Holliday', 'jackson holliday', 'BAL', '2B', ARRAY['2B', 'SS']::text[]),
  ('Jackson Merrill', 'jackson merrill', 'SD', 'OF', ARRAY['OF']::text[]),
  ('Jacob deGrom', 'jacob degrom', 'TEX', 'SP', ARRAY['SP']::text[]),
  ('Jacob Gonzalez', 'jacob gonzalez', 'PIT', '1B', ARRAY['1B', '2B', 'SS']::text[]),
  ('Jacob Latz', 'jacob latz', 'TEX', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Jacob Melton', 'jacob melton', 'TB', 'OF', ARRAY['OF']::text[]),
  ('Jacob Misiorowski', 'jacob misiorowski', 'MIL', 'SP', ARRAY['SP']::text[]),
  ('Jacob Wilson', 'jacob wilson', 'ATH', 'SS', ARRAY['SS']::text[]),
  ('Jacob Young', 'jacob young', 'WSH', 'OF', ARRAY['OF']::text[]),
  ('Jake Bauers', 'jake bauers', 'MIL', '1B', ARRAY['1B', 'OF']::text[]),
  ('Jake Bennett', 'jake bennett', 'BOS', 'SP', ARRAY['SP']::text[]),
  ('Jake Burger', 'jake burger', 'TEX', '1B', ARRAY['1B']::text[]),
  ('Jake Cronenworth', 'jake cronenworth', 'SD', '1B', ARRAY['1B', '2B', 'SS']::text[]),
  ('Jake Mangum', 'jake mangum', 'PIT', 'OF', ARRAY['OF']::text[]),
  ('Jake McCarthy', 'jake mccarthy', 'COL', 'OF', ARRAY['OF']::text[]),
  ('Jakob Marsee', 'jakob marsee', 'MIA', 'OF', ARRAY['OF']::text[]),
  ('James Wood', 'james wood', 'WSH', 'OF', ARRAY['OF']::text[]),
  ('Jared Jones', 'jared jones', 'PIT', 'SP', ARRAY['SP']::text[]),
  ('Jared Triolo', 'jared triolo', 'PIT', '1B', ARRAY['1B', '2B', '3B', 'SS']::text[]),
  ('Jared Young', 'jared young', 'NYM', '1B', ARRAY['1B', 'OF']::text[]),
  ('Jarren Duran', 'jarren duran', 'BOS', 'OF', ARRAY['OF']::text[]),
  ('Jasson Domínguez', 'jasson dominguez', 'NYY', 'OF', ARRAY['OF']::text[]),
  ('Javier Assad', 'javier assad', 'CHC', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Javier Sanoja', 'javier sanoja', 'MIA', '2B', ARRAY['2B', '3B', 'SS', 'OF']::text[]),
  ('Jazz Chisholm Jr.', 'jazz chisholm jr', 'NYY', '2B', ARRAY['2B', '3B']::text[]),
  ('Jeff Hoffman', 'jeff hoffman', 'TOR', 'RP', ARRAY['RP']::text[]),
  ('Jeff McNeil', 'jeff mcneil', 'ATH', '2B', ARRAY['2B', 'OF']::text[]),
  ('Jeffrey Springs', 'jeffrey springs', 'ATH', 'SP', ARRAY['SP']::text[]),
  ('Jeremiah Estrada', 'jeremiah estrada', 'SD', 'RP', ARRAY['RP']::text[]),
  ('Jeremiah Jackson', 'jeremiah jackson', 'BAL', '2B', ARRAY['2B', '3B', 'OF']::text[]),
  ('Jeremy Peña', 'jeremy pena', 'HOU', 'SS', ARRAY['SS']::text[]),
  ('Jesús Luzardo', 'jesus luzardo', 'PHI', 'SP', ARRAY['SP']::text[]),
  ('Jesús Sánchez', 'jesus sanchez', 'TOR', 'OF', ARRAY['OF']::text[]),
  ('Jhoan Duran', 'jhoan duran', 'PHI', 'RP', ARRAY['RP']::text[]),
  ('JJ Bleday', 'jj bleday', 'CIN', 'OF', ARRAY['OF']::text[]),
  ('JJ Wetherholt', 'jj wetherholt', 'STL', '2B', ARRAY['2B', '3B', 'SS']::text[]),
  ('Jo Adell', 'jo adell', 'LAA', 'OF', ARRAY['OF']::text[]),
  ('Joe Mack', 'joe mack', 'MIA', 'C', ARRAY['C']::text[]),
  ('Joe Musgrove', 'joe musgrove', 'SD', 'SP', ARRAY['SP']::text[]),
  ('Joe Ryan', 'joe ryan', 'MIN', 'SP', ARRAY['SP']::text[]),
  ('Joey Cantillo', 'joey cantillo', 'CLE', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Jonathan Aranda', 'jonathan aranda', 'TB', '1B', ARRAY['1B']::text[]),
  ('Jordan Lawlar', 'jordan lawlar', 'AZ', '3B', ARRAY['3B', 'OF']::text[]),
  ('Jordan Montgomery', 'jordan montgomery', 'TEX', 'SP', ARRAY['SP']::text[]),
  ('Jordan Walker', 'jordan walker', 'STL', 'OF', ARRAY['OF']::text[]),
  ('Jorge Soler', 'jorge soler', 'LAA', 'OF', ARRAY['OF']::text[]),
  ('Jose Altuve', 'jose altuve', 'HOU', '2B', ARRAY['2B', 'OF']::text[]),
  ('José Caballero', 'jose caballero', 'NYY', '2B', ARRAY['2B', '3B', 'SS', 'OF']::text[]),
  ('José Ramírez', 'jose ramirez', 'CLE', '3B', ARRAY['3B']::text[]),
  ('José Soriano', 'jose soriano', 'LAA', 'SP', ARRAY['SP']::text[]),
  ('Josh Bell', 'josh bell', 'MIN', '1B', ARRAY['1B']::text[]),
  ('Josh Hader', 'josh hader', 'HOU', 'RP', ARRAY['RP']::text[]),
  ('Josh Jung', 'josh jung', 'TEX', '3B', ARRAY['3B']::text[]),
  ('Josh Naylor', 'josh naylor', 'SEA', '1B', ARRAY['1B']::text[]),
  ('Josh Smith', 'josh smith', 'TEX', '1B', ARRAY['1B', '2B', '3B', 'SS', 'OF']::text[]),
  ('Joshua Baez', 'joshua baez', 'STL', 'OF', ARRAY['OF']::text[]),
  ('Joshua Kuroda-Grauer', 'joshua kuroda grauer', 'ATH', '3B', ARRAY['3B', 'SS']::text[]),
  ('Juan Morillo', 'juan morillo', 'AZ', 'RP', ARRAY['RP']::text[]),
  ('Juan Soto', 'juan soto', 'NYM', 'OF', ARRAY['OF']::text[]),
  ('Julio Rodríguez', 'julio rodriguez', 'SEA', 'OF', ARRAY['OF']::text[]),
  ('Jung Hoo Lee', 'jung hoo lee', 'SF', 'OF', ARRAY['OF']::text[]),
  ('Junior Caminero', 'junior caminero', 'TB', '3B', ARRAY['3B']::text[]),
  ('Justin Crawford', 'justin crawford', 'PHI', 'OF', ARRAY['OF']::text[]),
  ('Justin Wrobleski', 'justin wrobleski', 'LAD', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Kazuma Okamoto', 'kazuma okamoto', 'TOR', '1B', ARRAY['1B', '3B']::text[]),
  ('Keibert Ruiz', 'keibert ruiz', 'WSH', 'C', ARRAY['C']::text[]),
  ('Kenley Jansen', 'kenley jansen', 'DET', 'RP', ARRAY['RP']::text[]),
  ('Kerry Carpenter', 'kerry carpenter', 'DET', 'OF', ARRAY['OF']::text[]),
  ('Ketel Marte', 'ketel marte', 'AZ', '2B', ARRAY['2B']::text[]),
  ('Kevin Gausman', 'kevin gausman', 'TOR', 'SP', ARRAY['SP']::text[]),
  ('Kevin Ginkel', 'kevin ginkel', 'AZ', 'RP', ARRAY['RP']::text[]),
  ('Kevin Kelly', 'kevin kelly', 'TB', 'RP', ARRAY['RP']::text[]),
  ('Kevin McGonigle', 'kevin mcgonigle', 'DET', '3B', ARRAY['3B', 'SS']::text[]),
  ('Kody Clemens', 'kody clemens', 'MIN', '1B', ARRAY['1B', '2B', 'OF']::text[]),
  ('Konnor Griffin', 'konnor griffin', 'PIT', 'SS', ARRAY['SS', 'OF']::text[]),
  ('Kris Bubic', 'kris bubic', 'KC', 'SP', ARRAY['SP']::text[]),
  ('Kyle Bradish', 'kyle bradish', 'BAL', 'SP', ARRAY['SP']::text[]),
  ('Kyle Finnegan', 'kyle finnegan', 'DET', 'RP', ARRAY['RP']::text[]),
  ('Kyle Harrison', 'kyle harrison', 'MIL', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Kyle Higashioka', 'kyle higashioka', 'TEX', 'C', ARRAY['C']::text[]),
  ('Kyle Karros', 'kyle karros', 'COL', '3B', ARRAY['3B']::text[]),
  ('Kyle Leahy', 'kyle leahy', 'STL', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Kyle Manzardo', 'kyle manzardo', 'CLE', '1B', ARRAY['1B']::text[]),
  ('Kyle Schwarber', 'kyle schwarber', 'PHI', 'OF', ARRAY['OF']::text[]),
  ('Kyle Stowers', 'kyle stowers', 'MIA', '1B', ARRAY['1B', 'OF']::text[]),
  ('Kyle Teel', 'kyle teel', 'CWS', 'C', ARRAY['C']::text[]),
  ('Kyle Tucker', 'kyle tucker', 'LAD', 'OF', ARRAY['OF']::text[]),
  ('Landen Roupp', 'landen roupp', 'SF', 'SP', ARRAY['SP']::text[]),
  ('Lane Thomas', 'lane thomas', 'KC', 'OF', ARRAY['OF']::text[]),
  ('Lawrence Butler', 'lawrence butler', 'ATH', 'OF', ARRAY['OF']::text[]),
  ('Leo De Vries', 'leo de vries', 'ATH', 'SS', ARRAY['SS']::text[]),
  ('Liam Hicks', 'liam hicks', 'MIA', 'C', ARRAY['C', '1B']::text[]),
  ('Logan Gilbert', 'logan gilbert', 'SEA', 'SP', ARRAY['SP']::text[]),
  ('Logan Henderson', 'logan henderson', 'MIL', 'SP', ARRAY['SP']::text[]),
  ('Logan O''Hoppe', 'logan o hoppe', 'LAA', 'C', ARRAY['C']::text[]),
  ('Logan Webb', 'logan webb', 'SF', 'SP', ARRAY['SP']::text[]),
  ('Louis Varland', 'louis varland', 'TOR', 'RP', ARRAY['RP']::text[]),
  ('Lucas Erceg', 'lucas erceg', 'KC', 'RP', ARRAY['RP']::text[]),
  ('Luis Arraez', 'luis arraez', 'SF', '1B', ARRAY['1B', '2B']::text[]),
  ('Luis Campusano', 'luis campusano', 'SD', 'C', ARRAY['C']::text[]),
  ('Luis Castillo', 'luis castillo', 'SEA', 'SP', ARRAY['SP']::text[]),
  ('Luis García Jr.', 'luis garcia jr', 'WSH', '1B', ARRAY['1B', '2B']::text[]),
  ('Luis Lara', 'luis lara', 'MIL', 'OF', ARRAY['OF']::text[]),
  ('Luis Rengifo', 'luis rengifo', 'SD', '2B', ARRAY['2B', '3B', 'OF']::text[]),
  ('Luis Robert Jr.', 'luis robert jr', 'NYM', 'OF', ARRAY['OF']::text[]),
  ('Luis Severino', 'luis severino', 'ATH', 'SP', ARRAY['SP']::text[]),
  ('Luke Keaschall', 'luke keaschall', 'MIN', '2B', ARRAY['2B', 'OF']::text[]),
  ('Luke Raley', 'luke raley', 'SEA', '1B', ARRAY['1B', 'OF']::text[]),
  ('MacKenzie Gore', 'mackenzie gore', 'TEX', 'SP', ARRAY['SP']::text[]),
  ('Maikel Garcia', 'maikel garcia', 'KC', '2B', ARRAY['2B', '3B', 'SS', 'OF']::text[]),
  ('Manny Machado', 'manny machado', 'SD', '3B', ARRAY['3B']::text[]),
  ('Marcelo Mayer', 'marcelo mayer', 'BOS', '2B', ARRAY['2B', '3B', 'SS']::text[]),
  ('Marcus Semien', 'marcus semien', 'NYM', '2B', ARRAY['2B']::text[]),
  ('Mark Vientos', 'mark vientos', 'NYM', '1B', ARRAY['1B', '3B']::text[]),
  ('Masataka Yoshida', 'masataka yoshida', 'BOS', 'OF', ARRAY['OF']::text[]),
  ('Mason Miller', 'mason miller', 'SD', 'RP', ARRAY['RP']::text[]),
  ('Masyn Winn', 'masyn winn', 'STL', 'SS', ARRAY['SS']::text[]),
  ('Matt Brash', 'matt brash', 'SEA', 'RP', ARRAY['RP']::text[]),
  ('Matt Chapman', 'matt chapman', 'SF', '3B', ARRAY['3B']::text[]),
  ('Matt McLain', 'matt mclain', 'CIN', '2B', ARRAY['2B', 'SS']::text[]),
  ('Matt Olson', 'matt olson', 'ATL', '1B', ARRAY['1B']::text[]),
  ('Matt Strahm', 'matt strahm', 'KC', 'RP', ARRAY['RP']::text[]),
  ('Matthew Boyd', 'matthew boyd', 'CHC', 'SP', ARRAY['SP']::text[]),
  ('Matthew Liberatore', 'matthew liberatore', 'STL', 'SP', ARRAY['SP']::text[]),
  ('Mauricio Dubón', 'mauricio dubon', 'ATL', '2B', ARRAY['2B', '3B', 'SS', 'OF']::text[]),
  ('Max Clark', 'max clark', 'DET', 'OF', ARRAY['OF']::text[]),
  ('Max Fried', 'max fried', 'NYY', 'SP', ARRAY['SP']::text[]),
  ('Max Meyer', 'max meyer', 'MIA', 'SP', ARRAY['SP']::text[]),
  ('Max Muncy', 'max muncy', 'LAD', '3B', ARRAY['3B']::text[]),
  ('Merrill Kelly', 'merrill kelly', 'AZ', 'SP', ARRAY['SP']::text[]),
  ('Michael Busch', 'michael busch', 'CHC', '1B', ARRAY['1B']::text[]),
  ('Michael Harris II', 'michael harris ii', 'ATL', 'OF', ARRAY['OF']::text[]),
  ('Michael King', 'michael king', 'SD', 'SP', ARRAY['SP']::text[]),
  ('Michael Massey', 'michael massey', 'KC', '2B', ARRAY['2B', 'OF']::text[]),
  ('Michael McGreevy', 'michael mcgreevy', 'STL', 'SP', ARRAY['SP']::text[]),
  ('Michael Petersen', 'michael petersen', 'MIA', 'RP', ARRAY['RP']::text[]),
  ('Michael Soroka', 'michael soroka', 'AZ', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Michael Wacha', 'michael wacha', 'KC', 'SP', ARRAY['SP']::text[]),
  ('Mickey Moniak', 'mickey moniak', 'COL', 'OF', ARRAY['OF']::text[]),
  ('Miguel Andujar', 'miguel andujar', 'SD', '3B', ARRAY['3B', 'OF']::text[]),
  ('Miguel Vargas', 'miguel vargas', 'CWS', '1B', ARRAY['1B', '3B']::text[]),
  ('Mike Trout', 'mike trout', 'LAA', 'OF', ARRAY['OF']::text[]),
  ('Mitch Keller', 'mitch keller', 'PIT', 'SP', ARRAY['SP']::text[]),
  ('Mookie Betts', 'mookie betts', 'LAD', 'SS', ARRAY['SS']::text[]),
  ('Munetaka Murakami', 'munetaka murakami', 'CWS', '1B', ARRAY['1B', '3B']::text[]),
  ('Nasim Nuñez', 'nasim nunez', 'WSH', '2B', ARRAY['2B', 'SS']::text[]),
  ('Nathan Eovaldi', 'nathan eovaldi', 'TEX', 'SP', ARRAY['SP']::text[]),
  ('Nick Gonzales', 'nick gonzales', 'PIT', '2B', ARRAY['2B', '3B', 'SS']::text[]),
  ('Nick Kurtz', 'nick kurtz', 'ATH', '1B', ARRAY['1B']::text[]),
  ('Nick Lodolo', 'nick lodolo', 'CIN', 'SP', ARRAY['SP']::text[]),
  ('Nick Martinez', 'nick martinez', 'TB', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Nick Pivetta', 'nick pivetta', 'SD', 'SP', ARRAY['SP']::text[]),
  ('Nico Hoerner', 'nico hoerner', 'CHC', '2B', ARRAY['2B', 'SS']::text[]),
  ('Noah Schultz', 'noah schultz', 'CWS', 'SP', ARRAY['SP']::text[]),
  ('Noelvi Marte', 'noelvi marte', 'CIN', '3B', ARRAY['3B', 'OF']::text[]),
  ('Nolan Arenado', 'nolan arenado', 'AZ', '3B', ARRAY['3B']::text[]),
  ('Nolan McLean', 'nolan mclean', 'NYM', 'SP', ARRAY['SP']::text[]),
  ('Nolan Schanuel', 'nolan schanuel', 'LAA', '1B', ARRAY['1B']::text[]),
  ('Oneil Cruz', 'oneil cruz', 'PIT', 'OF', ARRAY['OF']::text[]),
  ('Orion Kerkering', 'orion kerkering', 'PHI', 'RP', ARRAY['RP']::text[]),
  ('Oswald Peraza', 'oswald peraza', 'LAA', '1B', ARRAY['1B', '2B', '3B', 'SS']::text[]),
  ('Otto Lopez', 'otto lopez', 'MIA', '2B', ARRAY['2B', 'SS']::text[]),
  ('Owen Caissie', 'owen caissie', 'MIA', 'OF', ARRAY['OF']::text[]),
  ('Ozzie Albies', 'ozzie albies', 'ATL', '2B', ARRAY['2B']::text[]),
  ('Parker Messick', 'parker messick', 'CLE', 'SP', ARRAY['SP']::text[]),
  ('Paul Goldschmidt', 'paul goldschmidt', 'NYY', '1B', ARRAY['1B']::text[]),
  ('Paul Sewald', 'paul sewald', 'AZ', 'RP', ARRAY['RP']::text[]),
  ('Paul Skenes', 'paul skenes', 'PIT', 'SP', ARRAY['SP']::text[]),
  ('Payton Tolle', 'payton tolle', 'BOS', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Pete Alonso', 'pete alonso', 'BAL', '1B', ARRAY['1B']::text[]),
  ('Pete Crow-Armstrong', 'pete crow armstrong', 'CHC', 'OF', ARRAY['OF']::text[]),
  ('Pete Fairbanks', 'pete fairbanks', 'MIA', 'RP', ARRAY['RP']::text[]),
  ('Peter Lambert', 'peter lambert', 'HOU', 'SP', ARRAY['SP']::text[]),
  ('Rafael Devers', 'rafael devers', 'SF', '1B', ARRAY['1B']::text[]),
  ('Raisel Iglesias', 'raisel iglesias', 'ATL', 'RP', ARRAY['RP']::text[]),
  ('Randy Arozarena', 'randy arozarena', 'SEA', 'OF', ARRAY['OF']::text[]),
  ('Ranger Suarez', 'ranger suarez', 'BOS', 'SP', ARRAY['SP']::text[]),
  ('Reid Detmers', 'reid detmers', 'LAA', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Reynaldo López', 'reynaldo lopez', 'ATL', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Rhys Hoskins', 'rhys hoskins', 'CLE', '1B', ARRAY['1B']::text[]),
  ('Rico Garcia', 'rico garcia', 'BAL', 'RP', ARRAY['RP']::text[]),
  ('Riley Greene', 'riley greene', 'DET', 'OF', ARRAY['OF']::text[]),
  ('Riley O''Brien', 'riley o brien', 'STL', 'RP', ARRAY['RP']::text[]),
  ('Robbie Ray', 'robbie ray', 'SF', 'SP', ARRAY['SP']::text[]),
  ('Robert Suarez', 'robert suarez', 'ATL', 'RP', ARRAY['RP']::text[]),
  ('Roki Sasaki', 'roki sasaki', 'LAD', 'SP', ARRAY['SP']::text[]),
  ('Ronald Acuña Jr.', 'ronald acuna jr', 'ATL', 'OF', ARRAY['OF']::text[]),
  ('Ronel Blanco', 'ronel blanco', 'HOU', 'SP', ARRAY['SP']::text[]),
  ('Royce Lewis', 'royce lewis', 'MIN', '1B', ARRAY['1B', '3B']::text[]),
  ('Ryan Jeffers', 'ryan jeffers', 'MIN', 'C', ARRAY['C']::text[]),
  ('Ryan McMahon', 'ryan mcmahon', 'NYY', '3B', ARRAY['3B']::text[]),
  ('Ryan O''Hearn', 'ryan o hearn', 'PIT', '1B', ARRAY['1B', 'OF']::text[]),
  ('Ryan Sloan', 'ryan sloan', 'SEA', 'SP', ARRAY['SP']::text[]),
  ('Ryan Waldschmidt', 'ryan waldschmidt', 'AZ', 'OF', ARRAY['OF']::text[]),
  ('Ryan Weathers', 'ryan weathers', 'NYY', 'SP', ARRAY['SP']::text[]),
  ('S. Ohtani (Pitcher)IL', 's ohtani pitcher il', 'LAD', 'SP', ARRAY['SP']::text[]),
  ('Sal Frelick', 'sal frelick', 'MIL', 'OF', ARRAY['OF']::text[]),
  ('Sal Stewart', 'sal stewart', 'CIN', '1B', ARRAY['1B', '2B', '3B']::text[]),
  ('Salvador Perez', 'salvador perez', 'KC', 'C', ARRAY['C', '1B']::text[]),
  ('Sam Antonacci', 'sam antonacci', 'CWS', '2B', ARRAY['2B', '3B', 'OF']::text[]),
  ('Samuel Basallo', 'samuel basallo', 'BAL', 'C', ARRAY['C']::text[]),
  ('Sandy Alcantara', 'sandy alcantara', 'MIA', 'SP', ARRAY['SP']::text[]),
  ('Sean Burke', 'sean burke', 'CWS', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Seiya Suzuki', 'seiya suzuki', 'CHC', 'OF', ARRAY['OF']::text[]),
  ('Seranthony Domínguez', 'seranthony dominguez', 'CWS', 'RP', ARRAY['RP']::text[]),
  ('Seth Halvorsen', 'seth halvorsen', 'LAD', 'RP', ARRAY['RP']::text[]),
  ('Seth Lugo', 'seth lugo', 'KC', 'SP', ARRAY['SP']::text[]),
  ('Shane Baz', 'shane baz', 'BAL', 'SP', ARRAY['SP']::text[]),
  ('Shane Bieber', 'shane bieber', 'TOR', 'SP', ARRAY['SP']::text[]),
  ('Shane Drohan', 'shane drohan', 'MIL', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Shane McClanahan', 'shane mcclanahan', 'TB', 'SP', ARRAY['SP']::text[]),
  ('Shawn Armstrong', 'shawn armstrong', 'CLE', 'RP', ARRAY['RP']::text[]),
  ('Shea Langeliers', 'shea langeliers', 'ATH', 'C', ARRAY['C']::text[]),
  ('Shohei Ohtani (Batter)', 'shohei ohtani batter', 'LAD', 'DH', ARRAY['DH']::text[]),
  ('Shota Imanaga', 'shota imanaga', 'CHC', 'SP', ARRAY['SP']::text[]),
  ('Slade Cecconi', 'slade cecconi', 'CLE', 'SP', ARRAY['SP']::text[]),
  ('Sonny Gray', 'sonny gray', 'BOS', 'SP', ARRAY['SP']::text[]),
  ('Spencer Horwitz', 'spencer horwitz', 'PIT', '1B', ARRAY['1B']::text[]),
  ('Spencer Schwellenbach', 'spencer schwellenbach', 'ATL', 'SP', ARRAY['SP']::text[]),
  ('Spencer Steer', 'spencer steer', 'CIN', '1B', ARRAY['1B', '2B', 'OF']::text[]),
  ('Spencer Strider', 'spencer strider', 'ATL', 'SP', ARRAY['SP']::text[]),
  ('Steven Kwan', 'steven kwan', 'CLE', 'OF', ARRAY['OF']::text[]),
  ('Taj Bradley', 'taj bradley', 'MIN', 'SP', ARRAY['SP']::text[]),
  ('Tanner Bibee', 'tanner bibee', 'CLE', 'SP', ARRAY['SP']::text[]),
  ('Tanner Scott', 'tanner scott', 'LAD', 'RP', ARRAY['RP']::text[]),
  ('Tarik Skubal', 'tarik skubal', 'DET', 'SP', ARRAY['SP']::text[]),
  ('Tatsuya Imai', 'tatsuya imai', 'HOU', 'SP', ARRAY['SP']::text[]),
  ('Taylor Rogers', 'taylor rogers', 'MIN', 'RP', ARRAY['RP']::text[]),
  ('Taylor Ward', 'taylor ward', 'BAL', 'OF', ARRAY['OF']::text[]),
  ('Tejay Antone', 'tejay antone', 'CIN', 'RP', ARRAY['RP']::text[]),
  ('Teoscar Hernández', 'teoscar hernandez', 'LAD', 'OF', ARRAY['OF']::text[]),
  ('Tim Tawa', 'tim tawa', 'AZ', '1B', ARRAY['1B', '2B', 'OF']::text[]),
  ('TJ Rumfield', 'tj rumfield', 'COL', '1B', ARRAY['1B']::text[]),
  ('Tommy White', 'tommy white', 'ATH', '3B', ARRAY['3B']::text[]),
  ('Travis Bazzana', 'travis bazzana', 'CLE', '2B', ARRAY['2B']::text[]),
  ('Trea Turner', 'trea turner', 'PHI', 'SS', ARRAY['SS']::text[]),
  ('Trent Grisham', 'trent grisham', 'NYY', 'OF', ARRAY['OF']::text[]),
  ('Trevor Larnach', 'trevor larnach', 'MIN', 'OF', ARRAY['OF']::text[]),
  ('Trevor Megill', 'trevor megill', 'MIL', 'RP', ARRAY['RP']::text[]),
  ('Trevor Rogers', 'trevor rogers', 'BAL', 'SP', ARRAY['SP']::text[]),
  ('Trevor Story', 'trevor story', 'BOS', 'SS', ARRAY['SS']::text[]),
  ('Trey Yesavage', 'trey yesavage', 'TOR', 'SP', ARRAY['SP']::text[]),
  ('Tristan Peters', 'tristan peters', 'CWS', 'OF', ARRAY['OF']::text[]),
  ('Troy Melton', 'troy melton', 'DET', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Ty France', 'ty france', 'SD', '1B', ARRAY['1B']::text[]),
  ('Tyler Glasnow', 'tyler glasnow', 'LAD', 'SP', ARRAY['SP']::text[]),
  ('Tyler Rogers', 'tyler rogers', 'TOR', 'RP', ARRAY['RP']::text[]),
  ('Tyler Soderstrom', 'tyler soderstrom', 'ATH', '1B', ARRAY['1B', 'OF']::text[]),
  ('Tyler Stephenson', 'tyler stephenson', 'CIN', 'C', ARRAY['C']::text[]),
  ('Tyler Wells', 'tyler wells', 'BAL', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Vaughn Grissom', 'vaughn grissom', 'LAA', '1B', ARRAY['1B', '2B', '3B']::text[]),
  ('Victor Caratini', 'victor caratini', 'MIN', 'C', ARRAY['C', '1B']::text[]),
  ('Vinnie Pasquantino', 'vinnie pasquantino', 'KC', '1B', ARRAY['1B']::text[]),
  ('Vladimir Guerrero Jr.', 'vladimir guerrero jr', 'TOR', '1B', ARRAY['1B']::text[]),
  ('Walbert Ureña', 'walbert urena', 'LAA', 'SP', ARRAY['SP']::text[]),
  ('Walker Buehler', 'walker buehler', 'SD', 'SP', ARRAY['SP']::text[]),
  ('Will Smith', 'will smith', 'LAD', 'C', ARRAY['C']::text[]),
  ('Will Warren', 'will warren', 'NYY', 'SP', ARRAY['SP']::text[]),
  ('Willi Castro', 'willi castro', 'COL', '1B', ARRAY['1B', '2B', '3B', 'SS', 'OF']::text[]),
  ('William Contreras', 'william contreras', 'MIL', 'C', ARRAY['C']::text[]),
  ('Willson Contreras', 'willson contreras', 'BOS', '1B', ARRAY['1B']::text[]),
  ('Willy Adames', 'willy adames', 'SF', 'SS', ARRAY['SS']::text[]),
  ('Wilyer Abreu', 'wilyer abreu', 'BOS', 'OF', ARRAY['OF']::text[]),
  ('Wyatt Langford', 'wyatt langford', 'TEX', 'OF', ARRAY['OF']::text[]),
  ('Xander Bogaerts', 'xander bogaerts', 'SD', 'SS', ARRAY['SS']::text[]),
  ('Xavier Edwards', 'xavier edwards', 'MIA', '2B', ARRAY['2B', 'SS']::text[]),
  ('Yainer Diaz', 'yainer diaz', 'HOU', 'C', ARRAY['C']::text[]),
  ('Yandy Díaz', 'yandy diaz', 'TB', '1B', ARRAY['1B']::text[]),
  ('Yoendrys Gómez', 'yoendrys gomez', 'MIN', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Yordan Alvarez', 'yordan alvarez', 'HOU', 'OF', ARRAY['OF']::text[]),
  ('Yoshinobu Yamamoto', 'yoshinobu yamamoto', 'LAD', 'SP', ARRAY['SP']::text[]),
  ('Zac Gallen', 'zac gallen', 'AZ', 'SP', ARRAY['SP']::text[]),
  ('Zach McKinstry', 'zach mckinstry', 'DET', '2B', ARRAY['2B', '3B', 'SS', 'OF']::text[]),
  ('Zach Neto', 'zach neto', 'LAA', 'SS', ARRAY['SS']::text[]),
  ('Zach Thornton', 'zach thornton', 'NYM', 'SP', ARRAY['SP']::text[]),
  ('Zack Gelof', 'zack gelof', 'ATH', '2B', ARRAY['2B', '3B', 'OF']::text[]),
  ('Zack Littell', 'zack littell', 'WSH', 'SP', ARRAY['SP', 'RP']::text[]),
  ('Zack Wheeler', 'zack wheeler', 'PHI', 'SP', ARRAY['SP']::text[]),
  ('Zebby Matthews', 'zebby matthews', 'MIN', 'SP', ARRAY['SP']::text[])
)
INSERT INTO mlb_players (
  display_name,
  normalized_name,
  primary_position,
  eligible_positions,
  mlb_team_id,
  active
)
SELECT
  player_seed.display_name,
  player_seed.normalized_name,
  player_seed.primary_position,
  player_seed.eligible_positions,
  mlb_teams.id,
  TRUE
FROM player_seed
JOIN mlb_teams ON mlb_teams.abbreviation = player_seed.mlb_abbreviation
ON CONFLICT (normalized_name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  primary_position = EXCLUDED.primary_position,
  eligible_positions = EXCLUDED.eligible_positions,
  mlb_team_id = EXCLUDED.mlb_team_id,
  active = TRUE,
  updated_at = NOW();

WITH current_season AS (
  SELECT id FROM seasons WHERE season_number = 32
)
DELETE FROM roster_memberships
USING current_season
WHERE roster_memberships.season_id = current_season.id
  AND roster_memberships.league_code = 'Keystone'
  AND roster_memberships.acquisition_type = 'admin'
  AND roster_memberships.acquired_on = DATE '2026-07-20'
  AND roster_memberships.released_on IS NULL;

WITH current_season AS (
  SELECT id FROM seasons WHERE season_number = 32
)
UPDATE roster_memberships
SET
  released_on = DATE '2026-07-20',
  release_type = 'admin',
  updated_at = NOW()
FROM current_season
WHERE roster_memberships.season_id = current_season.id
  AND roster_memberships.league_code = 'Keystone'
  AND roster_memberships.released_on IS NULL;

WITH current_season AS (
  SELECT id FROM seasons WHERE season_number = 32
),
roster_seed (team_nickname, normalized_name, source_row) AS (
  VALUES
  ('ALBATROSSES', 'alejandro kirk', 15),
  ('ALBATROSSES', 'alex lange', 471),
  ('ALBATROSSES', 'aroldis chapman', 468),
  ('ALBATROSSES', 'blake snell', 476),
  ('ALBATROSSES', 'bobby witt jr', 2),
  ('ALBATROSSES', 'christian walker', 6),
  ('ALBATROSSES', 'corey seager', 13),
  ('ALBATROSSES', 'dalton rushing', 12),
  ('ALBATROSSES', 'edwin diaz', 475),
  ('ALBATROSSES', 'framber valdez', 465),
  ('ALBATROSSES', 'gleyber torres', 14),
  ('ALBATROSSES', 'jake bauers', 4),
  ('ALBATROSSES', 'joshua baez', 16),
  ('ALBATROSSES', 'justin wrobleski', 464),
  ('ALBATROSSES', 'kevin kelly', 467),
  ('ALBATROSSES', 'kyle harrison', 466),
  ('ALBATROSSES', 'manny machado', 8),
  ('ALBATROSSES', 'mauricio dubon', 9),
  ('ALBATROSSES', 'max fried', 472),
  ('ALBATROSSES', 'randy arozarena', 3),
  ('ALBATROSSES', 'reynaldo lopez', 470),
  ('ALBATROSSES', 'riley o brien', 463),
  ('ALBATROSSES', 'royce lewis', 11),
  ('ALBATROSSES', 'sean burke', 462),
  ('ALBATROSSES', 'taylor ward', 7),
  ('ALBATROSSES', 'trey yesavage', 469),
  ('ALBATROSSES', 'troy melton', 473),
  ('ALBATROSSES', 'tyler glasnow', 474),
  ('ALBATROSSES', 'wilyer abreu', 5),
  ('ALBATROSSES', 'zack gelof', 10),
  ('APOCALYPSE', 'andre pallante', 452),
  ('APOCALYPSE', 'angel martinez', 27),
  ('APOCALYPSE', 'austin riley', 21),
  ('APOCALYPSE', 'cade cavalli', 447),
  ('APOCALYPSE', 'cal raleigh', 29),
  ('APOCALYPSE', 'clay holmes', 459),
  ('APOCALYPSE', 'connelly early', 453),
  ('APOCALYPSE', 'davis martin', 449),
  ('APOCALYPSE', 'devin williams', 457),
  ('APOCALYPSE', 'fernando tatis jr', 17),
  ('APOCALYPSE', 'garrett whitlock', 454),
  ('APOCALYPSE', 'henry bolte', 30),
  ('APOCALYPSE', 'isaac collins', 25),
  ('APOCALYPSE', 'isaac paredes', 19),
  ('APOCALYPSE', 'j t ginn', 448),
  ('APOCALYPSE', 'jacob latz', 451),
  ('APOCALYPSE', 'jake bennett', 458),
  ('APOCALYPSE', 'jakob marsee', 22),
  ('APOCALYPSE', 'jarren duran', 20),
  ('APOCALYPSE', 'jj bleday', 23),
  ('APOCALYPSE', 'joey cantillo', 450),
  ('APOCALYPSE', 'jordan montgomery', 461),
  ('APOCALYPSE', 'mookie betts', 28),
  ('APOCALYPSE', 'nico hoerner', 18),
  ('APOCALYPSE', 'raisel iglesias', 456),
  ('APOCALYPSE', 'ronel blanco', 460),
  ('APOCALYPSE', 'shane drohan', 455),
  ('APOCALYPSE', 'tommy white', 31),
  ('APOCALYPSE', 'tristan peters', 24),
  ('APOCALYPSE', 'vinnie pasquantino', 26),
  ('BOMBERS', 'agustin ramirez', 44),
  ('BOMBERS', 'blaze alexander', 42),
  ('BOMBERS', 'brooks lee', 38),
  ('BOMBERS', 'bryce eldridge', 41),
  ('BOMBERS', 'cam smith', 39),
  ('BOMBERS', 'charlie condon', 47),
  ('BOMBERS', 'cody bellinger', 34),
  ('BOMBERS', 'danny jansen', 45),
  ('BOMBERS', 'gerrit cole', 442),
  ('BOMBERS', 'grayson rodriguez', 444),
  ('BOMBERS', 'hunter gaddis', 440),
  ('BOMBERS', 'jj wetherholt', 36),
  ('BOMBERS', 'josh bell', 37),
  ('BOMBERS', 'juan soto', 35),
  ('BOMBERS', 'kevin ginkel', 441),
  ('BOMBERS', 'konnor griffin', 40),
  ('BOMBERS', 'kyle higashioka', 43),
  ('BOMBERS', 'kyle teel', 46),
  ('BOMBERS', 'landen roupp', 436),
  ('BOMBERS', 'matthew liberatore', 438),
  ('BOMBERS', 'max clark', 48),
  ('BOMBERS', 'michael king', 437),
  ('BOMBERS', 'pete alonso', 33),
  ('BOMBERS', 'pete crow armstrong', 32),
  ('BOMBERS', 'roki sasaki', 439),
  ('BOMBERS', 'seth halvorsen', 445),
  ('BOMBERS', 'spencer schwellenbach', 446),
  ('BOMBERS', 'spencer strider', 443),
  ('COBRAS', 'adrian morejon', 429),
  ('COBRAS', 'bryan baker', 427),
  ('COBRAS', 'bryan woo', 426),
  ('COBRAS', 'cristopher sanchez', 424),
  ('COBRAS', 'curtis mead', 55),
  ('COBRAS', 'drew rasmussen', 428),
  ('COBRAS', 'eury perez', 432),
  ('COBRAS', 'ezequiel duran', 56),
  ('COBRAS', 'francisco alvarez', 61),
  ('COBRAS', 'gregory soto', 430),
  ('COBRAS', 'ian happ', 52),
  ('COBRAS', 'jackson merrill', 54),
  ('COBRAS', 'jacob melton', 65),
  ('COBRAS', 'jared jones', 435),
  ('COBRAS', 'jose altuve', 57),
  ('COBRAS', 'joshua kuroda grauer', 63),
  ('COBRAS', 'ketel marte', 50),
  ('COBRAS', 'luis lara', 64),
  ('COBRAS', 'maikel garcia', 59),
  ('COBRAS', 'miguel vargas', 49),
  ('COBRAS', 'ryan jeffers', 60),
  ('COBRAS', 'ryan weathers', 431),
  ('COBRAS', 'tanner scott', 433),
  ('COBRAS', 'tj rumfield', 51),
  ('COBRAS', 'ty france', 58),
  ('COBRAS', 'willy adames', 53),
  ('COBRAS', 'yainer diaz', 62),
  ('COBRAS', 'zack wheeler', 425),
  ('COBRAS', 'zebby matthews', 434),
  ('DIABLOS', 'alex vesia', 418),
  ('DIABLOS', 'brice turang', 67),
  ('DIABLOS', 'bryce miller', 421),
  ('DIABLOS', 'cj abrams', 66),
  ('DIABLOS', 'cole carrigg', 81),
  ('DIABLOS', 'dominic canzone', 79),
  ('DIABLOS', 'emilio pagan', 422),
  ('DIABLOS', 'evan phillips', 423),
  ('DIABLOS', 'fernando cruz', 416),
  ('DIABLOS', 'foster griffin', 413),
  ('DIABLOS', 'gabriel moreno', 80),
  ('DIABLOS', 'gavin williams', 412),
  ('DIABLOS', 'hyeseong kim', 82),
  ('DIABLOS', 'jackson chourio', 74),
  ('DIABLOS', 'jake burger', 73),
  ('DIABLOS', 'jo adell', 75),
  ('DIABLOS', 'juan morillo', 420),
  ('DIABLOS', 'luis garcia jr', 71),
  ('DIABLOS', 'max muncy', 72),
  ('DIABLOS', 'michael harris ii', 70),
  ('DIABLOS', 'munetaka murakami', 76),
  ('DIABLOS', 'seth lugo', 414),
  ('DIABLOS', 'shea langeliers', 69),
  ('DIABLOS', 'tarik skubal', 415),
  ('DIABLOS', 'travis bazzana', 78),
  ('DIABLOS', 'walker buehler', 419),
  ('DIABLOS', 'willson contreras', 68),
  ('DIABLOS', 'xander bogaerts', 77),
  ('DIABLOS', 'yoendrys gomez', 417),
  ('HACKERS', 'aaron ashby', 401),
  ('HACKERS', 'alec burleson', 88),
  ('HACKERS', 'andrew kittredge', 410),
  ('HACKERS', 'andy pages', 87),
  ('HACKERS', 'bailey ober', 407),
  ('HACKERS', 'blaze jordan', 97),
  ('HACKERS', 'brandon pfaadt', 408),
  ('HACKERS', 'brendan donovan', 96),
  ('HACKERS', 'bryce elder', 402),
  ('HACKERS', 'casey mize', 406),
  ('HACKERS', 'david bednar', 403),
  ('HACKERS', 'eduardo valencia', 98),
  ('HACKERS', 'george kirby', 400),
  ('HACKERS', 'hunter goodman', 86),
  ('HACKERS', 'ildemaro vargas', 91),
  ('HACKERS', 'justin crawford', 93),
  ('HACKERS', 'kody clemens', 89),
  ('HACKERS', 'kyle stowers', 90),
  ('HACKERS', 'michael soroka', 404),
  ('HACKERS', 'nick kurtz', 83),
  ('HACKERS', 'nick lodolo', 409),
  ('HACKERS', 'oswald peraza', 94),
  ('HACKERS', 'parker messick', 399),
  ('HACKERS', 'paul skenes', 398),
  ('HACKERS', 'sal stewart', 84),
  ('HACKERS', 'shane mcclanahan', 405),
  ('HACKERS', 'spencer horwitz', 92),
  ('HACKERS', 'tejay antone', 411),
  ('HACKERS', 'tyler stephenson', 95),
  ('HACKERS', 'zach neto', 85),
  ('HERMANOS', 'aj smith shawver', 397),
  ('HERMANOS', 'andres munoz', 388),
  ('HERMANOS', 'ben brown', 392),
  ('HERMANOS', 'bo bichette', 104),
  ('HERMANOS', 'brandon lowe', 101),
  ('HERMANOS', 'cade smith', 384),
  ('HERMANOS', 'chandler simpson', 106),
  ('HERMANOS', 'colt emerson', 111),
  ('HERMANOS', 'corbin carroll', 100),
  ('HERMANOS', 'dansby swanson', 102),
  ('HERMANOS', 'drake baldwin', 103),
  ('HERMANOS', 'grant holmes', 390),
  ('HERMANOS', 'heliot ramos', 107),
  ('HERMANOS', 'jake cronenworth', 114),
  ('HERMANOS', 'jared young', 112),
  ('HERMANOS', 'jasson dominguez', 113),
  ('HERMANOS', 'kenley jansen', 394),
  ('HERMANOS', 'kevin gausman', 386),
  ('HERMANOS', 'lawrence butler', 108),
  ('HERMANOS', 'logan henderson', 395),
  ('HERMANOS', 'logan o hoppe', 110),
  ('HERMANOS', 'nathan eovaldi', 385),
  ('HERMANOS', 'nick pivetta', 396),
  ('HERMANOS', 'tanner bibee', 387),
  ('HERMANOS', 'tatsuya imai', 393),
  ('HERMANOS', 'trevor rogers', 389),
  ('HERMANOS', 'vaughn grissom', 109),
  ('HERMANOS', 'vladimir guerrero jr', 105),
  ('HERMANOS', 'walbert urena', 391),
  ('HERMANOS', 'yordan alvarez', 99),
  ('HIGHLANDERS', 'aaron judge', 123),
  ('HIGHLANDERS', 'antonio senzatela', 379),
  ('HIGHLANDERS', 'austin wells', 131),
  ('HIGHLANDERS', 'bryson stott', 116),
  ('HIGHLANDERS', 'chase delauter', 119),
  ('HIGHLANDERS', 'david hamilton', 128),
  ('HIGHLANDERS', 'eduardo rodriguez', 373),
  ('HIGHLANDERS', 'eugenio suarez', 127),
  ('HIGHLANDERS', 'gavin sheets', 121),
  ('HIGHLANDERS', 'jake mangum', 126),
  ('HIGHLANDERS', 'joe mack', 130),
  ('HIGHLANDERS', 'jordan lawlar', 132),
  ('HIGHLANDERS', 'jose caballero', 124),
  ('HIGHLANDERS', 'jung hoo lee', 117),
  ('HIGHLANDERS', 'kyle finnegan', 381),
  ('HIGHLANDERS', 'logan webb', 375),
  ('HIGHLANDERS', 'lucas erceg', 377),
  ('HIGHLANDERS', 'luke keaschall', 120),
  ('HIGHLANDERS', 'mackenzie gore', 374),
  ('HIGHLANDERS', 'masyn winn', 122),
  ('HIGHLANDERS', 'matthew boyd', 382),
  ('HIGHLANDERS', 'michael busch', 115),
  ('HIGHLANDERS', 'robert suarez', 380),
  ('HIGHLANDERS', 'ryan sloan', 383),
  ('HIGHLANDERS', 'sal frelick', 125),
  ('HIGHLANDERS', 'shane baz', 376),
  ('HIGHLANDERS', 'trent grisham', 118),
  ('HIGHLANDERS', 'zach mckinstry', 129),
  ('HIGHLANDERS', 'zack littell', 378),
  ('HOPHEADS', 'andrew vaughn', 146),
  ('HOPHEADS', 'brad keller', 367),
  ('HOPHEADS', 'brandon marsh', 135),
  ('HOPHEADS', 'caleb durbin', 140),
  ('HOPHEADS', 'camilo doval', 369),
  ('HOPHEADS', 'christian yelich', 142),
  ('HOPHEADS', 'cole young', 137),
  ('HOPHEADS', 'daniel palencia', 371),
  ('HOPHEADS', 'dylan crews', 147),
  ('HOPHEADS', 'emmet sheehan', 366),
  ('HOPHEADS', 'francisco lindor', 149),
  ('HOPHEADS', 'jacob degrom', 362),
  ('HOPHEADS', 'jake mccarthy', 134),
  ('HOPHEADS', 'joe musgrove', 372),
  ('HOPHEADS', 'jose soriano', 361),
  ('HOPHEADS', 'josh naylor', 139),
  ('HOPHEADS', 'kerry carpenter', 145),
  ('HOPHEADS', 'kyle bradish', 363),
  ('HOPHEADS', 'marcelo mayer', 148),
  ('HOPHEADS', 'matt chapman', 141),
  ('HOPHEADS', 'matt strahm', 368),
  ('HOPHEADS', 'merrill kelly', 365),
  ('HOPHEADS', 'rhys hoskins', 143),
  ('HOPHEADS', 's ohtani pitcher il', 364),
  ('HOPHEADS', 'shawn armstrong', 370),
  ('HOPHEADS', 'shohei ohtani batter', 133),
  ('HOPHEADS', 'teoscar hernandez', 144),
  ('HOPHEADS', 'trevor story', 150),
  ('HOPHEADS', 'william contreras', 138),
  ('HOPHEADS', 'xavier edwards', 136),
  ('LEOPARDS', 'abner uribe', 352),
  ('LEOPARDS', 'brett baty', 161),
  ('LEOPARDS', 'bryan king', 354),
  ('LEOPARDS', 'carlos lagrange', 360),
  ('LEOPARDS', 'ceddanne rafaela', 157),
  ('LEOPARDS', 'chase burns', 349),
  ('LEOPARDS', 'chris sale', 350),
  ('LEOPARDS', 'dillon dingler', 155),
  ('LEOPARDS', 'ernie clement', 160),
  ('LEOPARDS', 'freddie freeman', 152),
  ('LEOPARDS', 'garrett crochet', 359),
  ('LEOPARDS', 'george springer', 163),
  ('LEOPARDS', 'geraldo perdomo', 159),
  ('LEOPARDS', 'ivan herrera', 154),
  ('LEOPARDS', 'jack perkins', 357),
  ('LEOPARDS', 'jeremiah estrada', 358),
  ('LEOPARDS', 'jonathan aranda', 151),
  ('LEOPARDS', 'kyle tucker', 156),
  ('LEOPARDS', 'liam hicks', 158),
  ('LEOPARDS', 'matt mclain', 162),
  ('LEOPARDS', 'michael massey', 164),
  ('LEOPARDS', 'miguel andujar', 165),
  ('LEOPARDS', 'noelvi marte', 167),
  ('LEOPARDS', 'orion kerkering', 355),
  ('LEOPARDS', 'payton tolle', 353),
  ('LEOPARDS', 'ranger suarez', 351),
  ('LEOPARDS', 'riley greene', 153),
  ('LEOPARDS', 'ryan waldschmidt', 166),
  ('LEOPARDS', 'sandy alcantara', 348),
  ('LEOPARDS', 'seranthony dominguez', 356),
  ('PEREGRINES', 'ben joyce', 347),
  ('PEREGRINES', 'braden montgomery', 182),
  ('PEREGRINES', 'carson benge', 172),
  ('PEREGRINES', 'carter jensen', 174),
  ('PEREGRINES', 'cooper pratt', 184),
  ('PEREGRINES', 'daylen lile', 171),
  ('PEREGRINES', 'esmerlyn valdez', 181),
  ('PEREGRINES', 'gage jump', 344),
  ('PEREGRINES', 'garrett cleavinger', 341),
  ('PEREGRINES', 'harry ford', 185),
  ('PEREGRINES', 'hunter brown', 345),
  ('PEREGRINES', 'jacob gonzalez', 183),
  ('PEREGRINES', 'jacob misiorowski', 336),
  ('PEREGRINES', 'jesus luzardo', 337),
  ('PEREGRINES', 'josh hader', 342),
  ('PEREGRINES', 'josh jung', 176),
  ('PEREGRINES', 'junior caminero', 168),
  ('PEREGRINES', 'kevin mcgonigle', 169),
  ('PEREGRINES', 'kris bubic', 343),
  ('PEREGRINES', 'kyle karros', 175),
  ('PEREGRINES', 'kyle manzardo', 179),
  ('PEREGRINES', 'max meyer', 338),
  ('PEREGRINES', 'rafael devers', 170),
  ('PEREGRINES', 'reid detmers', 339),
  ('PEREGRINES', 'sam antonacci', 177),
  ('PEREGRINES', 'samuel basallo', 178),
  ('PEREGRINES', 'tyler soderstrom', 173),
  ('PEREGRINES', 'tyler wells', 340),
  ('PEREGRINES', 'wyatt langford', 180),
  ('PEREGRINES', 'zach thornton', 346),
  ('RAIDERS', 'aaron nola', 328),
  ('RAIDERS', 'andrew abbott', 329),
  ('RAIDERS', 'andrew benintendi', 195),
  ('RAIDERS', 'brandon nimmo', 193),
  ('RAIDERS', 'byron buxton', 188),
  ('RAIDERS', 'carson kelly', 197),
  ('RAIDERS', 'colson montgomery', 190),
  ('RAIDERS', 'colton cowser', 200),
  ('RAIDERS', 'david peterson', 334),
  ('RAIDERS', 'grant taylor', 330),
  ('RAIDERS', 'gunnar henderson', 191),
  ('RAIDERS', 'hunter greene', 335),
  ('RAIDERS', 'jeff mcneil', 201),
  ('RAIDERS', 'jeffrey springs', 332),
  ('RAIDERS', 'jeremiah jackson', 203),
  ('RAIDERS', 'joe ryan', 326),
  ('RAIDERS', 'luke raley', 196),
  ('RAIDERS', 'marcus semien', 198),
  ('RAIDERS', 'mark vientos', 202),
  ('RAIDERS', 'matt olson', 186),
  ('RAIDERS', 'michael wacha', 327),
  ('RAIDERS', 'mike trout', 189),
  ('RAIDERS', 'nasim nunez', 194),
  ('RAIDERS', 'oneil cruz', 192),
  ('RAIDERS', 'otto lopez', 187),
  ('RAIDERS', 'pete fairbanks', 333),
  ('RAIDERS', 'tyler rogers', 331),
  ('RAIDERS', 'victor caratini', 199),
  ('RAIDERS', 'will smith', 204),
  ('RAIDERS', 'yoshinobu yamamoto', 325),
  ('ROGUES', 'brayan rocchio', 210),
  ('ROGUES', 'bryce harper', 206),
  ('ROGUES', 'cam schlittler', 313),
  ('ROGUES', 'casey schmitt', 207),
  ('ROGUES', 'christian scott', 321),
  ('ROGUES', 'dean kremer', 324),
  ('ROGUES', 'edward cabrera', 320),
  ('ROGUES', 'garrett mitchell', 208),
  ('ROGUES', 'george lombard jr', 222),
  ('ROGUES', 'jac caglianone', 209),
  ('ROGUES', 'jackson holliday', 218),
  ('ROGUES', 'jacob wilson', 217),
  ('ROGUES', 'james wood', 205),
  ('ROGUES', 'javier assad', 322),
  ('ROGUES', 'javier sanoja', 216),
  ('ROGUES', 'jhoan duran', 316),
  ('ROGUES', 'kyle leahy', 319),
  ('ROGUES', 'leo de vries', 221),
  ('ROGUES', 'luis campusano', 219),
  ('ROGUES', 'mason miller', 315),
  ('ROGUES', 'michael mcgreevy', 318),
  ('ROGUES', 'nick gonzales', 211),
  ('ROGUES', 'noah schultz', 323),
  ('ROGUES', 'nolan arenado', 212),
  ('ROGUES', 'nolan mclean', 314),
  ('ROGUES', 'owen caissie', 213),
  ('ROGUES', 'paul sewald', 317),
  ('ROGUES', 'ronald acuna jr', 215),
  ('ROGUES', 'salvador perez', 214),
  ('ROGUES', 'tim tawa', 220),
  ('SLAYERS', 'adley rutschman', 233),
  ('SLAYERS', 'alec bohm', 232),
  ('SLAYERS', 'alex bregman', 230),
  ('SLAYERS', 'anthony seigler', 241),
  ('SLAYERS', 'anthony volpe', 240),
  ('SLAYERS', 'austin martin', 238),
  ('SLAYERS', 'brandon valenzuela', 239),
  ('SLAYERS', 'brandon young', 308),
  ('SLAYERS', 'cedric mullins', 236),
  ('SLAYERS', 'chris bassitt', 312),
  ('SLAYERS', 'colin rea', 309),
  ('SLAYERS', 'dylan cease', 303),
  ('SLAYERS', 'heriberto hernandez', 237),
  ('SLAYERS', 'jeff hoffman', 306),
  ('SLAYERS', 'jordan walker', 224),
  ('SLAYERS', 'jorge soler', 235),
  ('SLAYERS', 'julio rodriguez', 228),
  ('SLAYERS', 'kyle schwarber', 223),
  ('SLAYERS', 'luis robert jr', 242),
  ('SLAYERS', 'ozzie albies', 225),
  ('SLAYERS', 'paul goldschmidt', 234),
  ('SLAYERS', 'peter lambert', 307),
  ('SLAYERS', 'robbie ray', 305),
  ('SLAYERS', 'ryan o hearn', 229),
  ('SLAYERS', 'sonny gray', 304),
  ('SLAYERS', 'spencer steer', 231),
  ('SLAYERS', 'taylor rogers', 311),
  ('SLAYERS', 'trea turner', 227),
  ('SLAYERS', 'yandy diaz', 226),
  ('SLAYERS', 'zac gallen', 310),
  ('SPIDERS', 'braxton ashcraft', 289),
  ('SPIDERS', 'bryan abreu', 299),
  ('SPIDERS', 'bryan reynolds', 243),
  ('SPIDERS', 'bubba chandler', 297),
  ('SPIDERS', 'carlos rodon', 300),
  ('SPIDERS', 'chase meidroth', 247),
  ('SPIDERS', 'dustin may', 292),
  ('SPIDERS', 'freddy peralta', 293),
  ('SPIDERS', 'gary sanchez', 254),
  ('SPIDERS', 'griffin canning', 301),
  ('SPIDERS', 'ha seong kim', 258),
  ('SPIDERS', 'jacob young', 248),
  ('SPIDERS', 'jared triolo', 255),
  ('SPIDERS', 'jazz chisholm jr', 245),
  ('SPIDERS', 'jeremy pena', 250),
  ('SPIDERS', 'jose ramirez', 246),
  ('SPIDERS', 'josh smith', 257),
  ('SPIDERS', 'keibert ruiz', 251),
  ('SPIDERS', 'luis arraez', 244),
  ('SPIDERS', 'luis castillo', 298),
  ('SPIDERS', 'luis rengifo', 256),
  ('SPIDERS', 'masataka yoshida', 252),
  ('SPIDERS', 'matt brash', 302),
  ('SPIDERS', 'michael petersen', 296),
  ('SPIDERS', 'nick martinez', 294),
  ('SPIDERS', 'rico garcia', 295),
  ('SPIDERS', 'ryan mcmahon', 253),
  ('SPIDERS', 'shota imanaga', 291),
  ('SPIDERS', 'steven kwan', 249),
  ('SPIDERS', 'taj bradley', 290),
  ('VIXENS', 'a j ewing', 272),
  ('VIXENS', 'addison barger', 275),
  ('VIXENS', 'andres gimenez', 270),
  ('VIXENS', 'ben rice', 259),
  ('VIXENS', 'brady singer', 284),
  ('VIXENS', 'colt keith', 271),
  ('VIXENS', 'daulton varsho', 265),
  ('VIXENS', 'elly de la cruz', 260),
  ('VIXENS', 'emerson hancock', 278),
  ('VIXENS', 'griffin jax', 286),
  ('VIXENS', 'hogan harris', 281),
  ('VIXENS', 'j p crawford', 266),
  ('VIXENS', 'j t realmuto', 273),
  ('VIXENS', 'jack flaherty', 285),
  ('VIXENS', 'jesus sanchez', 274),
  ('VIXENS', 'kazuma okamoto', 261),
  ('VIXENS', 'lane thomas', 268),
  ('VIXENS', 'logan gilbert', 276),
  ('VIXENS', 'louis varland', 277),
  ('VIXENS', 'luis severino', 287),
  ('VIXENS', 'mickey moniak', 267),
  ('VIXENS', 'mitch keller', 282),
  ('VIXENS', 'nolan schanuel', 269),
  ('VIXENS', 'seiya suzuki', 262),
  ('VIXENS', 'shane bieber', 288),
  ('VIXENS', 'slade cecconi', 283),
  ('VIXENS', 'trevor larnach', 264),
  ('VIXENS', 'trevor megill', 279),
  ('VIXENS', 'will warren', 280),
  ('VIXENS', 'willi castro', 263)
)
INSERT INTO roster_memberships (
  season_id,
  team_id,
  league_code,
  player_id,
  acquired_on,
  acquisition_type
)
SELECT
  current_season.id,
  teams.id,
  'Keystone',
  mlb_players.id,
  DATE '2026-07-20',
  'admin'
FROM roster_seed
CROSS JOIN current_season
JOIN teams ON UPPER(teams.nickname) = roster_seed.team_nickname
JOIN season_team_assignments sta
  ON sta.season_id = current_season.id
  AND sta.team_id = teams.id
  AND LOWER(sta.league_code) = LOWER('Keystone')
JOIN mlb_players ON mlb_players.normalized_name = roster_seed.normalized_name;

COMMIT;

SELECT
  teams.name AS team_name,
  COUNT(roster_memberships.id) AS active_players
FROM roster_memberships
JOIN seasons ON seasons.id = roster_memberships.season_id
JOIN teams ON teams.id = roster_memberships.team_id
WHERE seasons.season_number = 32
  AND roster_memberships.league_code = 'Keystone'
  AND roster_memberships.released_on IS NULL
GROUP BY teams.name
ORDER BY teams.name;
