-- Optional team profile metadata for public team pages.
-- Run after supabase/schema.sql.

CREATE TABLE IF NOT EXISTS team_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES teams(id),
  season_id BIGINT NULL REFERENCES seasons(id),
  owner_name VARCHAR(160) NULL,
  established_year INT NULL,
  banner_image_url TEXT NULL,
  logo_image_url TEXT NULL,
  accent_image_url TEXT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_team_profiles_team_season UNIQUE (team_id, season_id)
);

CREATE OR REPLACE VIEW public_team_profiles AS
SELECT
  t.id AS team_id,
  t.name AS team_name,
  lower(replace(t.name, ' ', '-')) AS team_slug,
  p.owner_name,
  p.established_year,
  p.banner_image_url,
  p.logo_image_url,
  p.accent_image_url,
  sta.league_code,
  sta.conference_code,
  sta.division_code,
  s.season_number
FROM teams t
LEFT JOIN team_profiles p ON p.team_id = t.id AND p.active = TRUE
LEFT JOIN season_team_assignments sta ON sta.team_id = t.id
LEFT JOIN seasons s ON s.id = sta.season_id;

GRANT SELECT ON public_team_profiles TO anon, authenticated;
