-- Yahoo Fantasy Sports OAuth storage.
-- Run this before using /admin-yahoo.html.

CREATE TABLE IF NOT EXISTS public.yahoo_oauth_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  yahoo_guid TEXT NULL,
  scopes TEXT NULL,
  token_type TEXT NULL,
  access_token JSONB NOT NULL,
  refresh_token JSONB NULL,
  expires_at TIMESTAMP WITH TIME ZONE NULL,
  profile JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_yahoo_oauth_connections_user UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS ix_yahoo_oauth_connections_user
  ON public.yahoo_oauth_connections (user_id);

ALTER TABLE public.yahoo_oauth_connections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No browser access to yahoo oauth connections" ON public.yahoo_oauth_connections;
CREATE POLICY "No browser access to yahoo oauth connections"
ON public.yahoo_oauth_connections
FOR ALL
TO anon, authenticated
USING (FALSE)
WITH CHECK (FALSE);

REVOKE ALL ON public.yahoo_oauth_connections FROM anon;
REVOKE ALL ON public.yahoo_oauth_connections FROM authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.yahoo_oauth_connections TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.yahoo_oauth_connections_id_seq TO service_role;
